### ISSUE TITLE
Unique instance

### ISSUE THREAD

**Issue by limatheus** [MetinSeylan/Vue-Socket.io#1]
Hi! @MetinSeylan 
Thank you for this great package!
In a normal flow, works pretty awesome!
But in my flow, I need start the socket connection when the application starts, I put the connection in my `main.js`... ok until here... when I open the application window I can see the connection was made in the server console.
I want to use the connection that was opened when the application was started in other application places... Eg. on the dashboard component  and set his own listeners on the `sockets { }`.
This is possible? you know a way to do that?
 
Best regards

**Comment by MetinSeylan** [comment]
@limatheus thank you!. It is currently not possible but this is nice idea and add this option soon
