### ISSUE TITLE
[Question] Does this lib work for connecting a native websocket server?

### ISSUE THREAD

**Issue by jasonwang178** [MetinSeylan/Vue-Socket.io#101]
Hi,

Does this lib work for connecting a native websocket server which not implemented via socket.io?

I ask this because I see the chrome console is telling it is connecting to http://localhost:4331/socket.io/?xxxx. This is not the real WS server location (http://localhost:4331/ is right the real one).

If so, anyone knows how to customize it to make it happen? Many thanks!

**Comment by ChauskinRodion** [comment]
hello @jasonwang178 
I'm not sure my answer is correct, but it seems to be working. [Taken here.](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-custom-path)
```
import socketio from 'socket.io-client'
Vue.use(VueSocketio, socketio('http://localhost:3000', { path: '/cable' }))
```
