### ISSUE TITLE
Receving Data From Server Not Working

### ISSUE THREAD

**Issue by aperezdx** [MetinSeylan/Vue-Socket.io#103]
I currently have a Python Flask SocketIO application that will be connecting to a Vue app. The Vue app (currently) will poll the Python application using socket.io on a button press. I can correctly receive the data sent from Vue; however, Vue is not receiving the data. Currently, my actions/mutations looks like this:

```const actions = {
  fbCommentsPerPost: (context) => {
    console.log('fb comments per post sent!')
    socket.emit('fb comments per post', { post_id: '123' })
    // socket.on('data', function (resp) {
    //   console.log(resp)
    // })
  },
  socket_connectResp: (context, message) => {
    console.log(message)
  },
  socket_fbData: (context, message) => {
    console.log(message)
  }
}

// mutations
const mutations = {
  SOCKET_FB_DATA: (state, status) => {
    console.log('comments!!!!')
  }
}
```

Using the README for this project, the `socket_fbData` _should_ be receiving the data from the Python app (the backend is emitting 'fb data'). When I run a simple client in node using `socket.io-client`, this works and I can properly receive data. Moreover, when I uncomment the socket.on block in `fbCommentsPerPost`, I can at least console log the data. Is there something I'm missing here?

**Comment by Baconiser** [comment]
Hi, 
i just ran into the same problem. Just use it as follows: 
this.$options.sockets.data = (data) => {
    console.log(data)
}

**Comment by NasskalteJuni** [comment]
I have a similar problem regarding the Vuex-Socket-Actions. I tried every possible upper/camel/lowercase variant of my names and could not get the actions working. The mutations receive the socket-events. 

(I have a socket hello-event, that is sent when a new user logs in)

This works:
...
```
mutations: {
   SOCKET_HELLO: (state, msg) => console.log('SOCKET_HELLO-Mutation', msg)
}
```
...

These don't:
...
```
actions: {
    socket_hello: ({commit}, msg) => console.log('socket-hello-action', msg), //officially described way
    socket_Hello: ({commit}, msg) => console.log('socket-hello-action', msg),
    socket_HELLO: ({commit}, msg) => console.log('socket-hello-action',msg),
    SOCKET_HELLO: ({commit}, msg) => console.log('socket-hello-action', msg)
}
```
...

**Comment by NasskalteJuni** [comment]
Ah, this is already part of another [issue](https://github.com/MetinSeylan/Vue-Socket.io/issues/117)
