### ISSUE TITLE
How to change timeout/heartbeat settings?

### ISSUE THREAD

**Issue by JAB-Freeware** [MetinSeylan/Vue-Socket.io#105]
I want to be able to display a "connection issues" message if the connection times out. Disconnect event only fires after about a minute. This is way too long. I need it to fire if the connection is lost for more than a few seconds. Is there a way to do this or would I have to modify your code manually?

Thanks, awesome library btw.

**Comment by voicenter** [comment]
That work for us  , configurations is an static object with our customer values  
 
```

const socket = io(configurations.socketURL);
socket.io.timeout(configurations.socketTimeout);
socket.io.reconnectionDelay(configurations.socketReconnectionDelay);
socket.io.reconnectionDelayMax(configurations.socketReconnectionDelayMax);

Vue.use(VueSocketio, **socket**);
```
, just use the socket object instead of the string url on the  VueSocketio init ...

**Comment by JAB-Freeware** [comment]
Thank you you're awesome

**Comment by JAB-Freeware** [comment]
@xeroxstar Yes its var IO = require...

I haven't used this lib in forever. Its probably something like require socket io. Look at the documentation/examples
