### ISSUE TITLE
Is it possible to use this plug-in as script distribution?

### ISSUE THREAD

**Issue by sreecodeslayer** [MetinSeylan/Vue-Socket.io#107]
How can I use this plug-in without actually configuring npm to serve the files?
I am currently using a Python Flask backend server
Like, can I use this the way vue-router and vue-resource are used, by simply fetching via a script tag?
Referencing a similar [plugin issue](https://github.com/shershen08/vue-masonry/issues/47) that I was able to build as a script distribution as well.  

I did build this one, and added it as script as I did for the abv mentioned plugin.
`Vue.use(VueSocketIo, 'http://localhost')` didn't throw any error, but connection doesn't happen. So I manually gave the `io('http://localhost')`, which kind of worked (I mean I was able to trigger the server side view function) for `connect`.
```
var App = new Vue({
	router,
	el:'#app',
	delimiters:['[[',']]'],
	data:{
	},
	sockets:{
		connect: function(){
			console.log("Connected")
		}
	},
	beforeMount(){
		this.initialLoad()
	},
	methods:{
		initialLoad: function(){
			console.log("Loaded...")
			this.$sockets.emit('test',{})
		}
	}
})
```
However, I don't see the console logs, `Connected` from sockets > connect, and then the `TypeError: Cannot read property 'emit' of undefined`

Am not a JS expert, and am new to Vue as well. Is there anything wrong in the code

**Comment by notchris** [comment]
I'm trying to do this as well. I don't think Vue is receiving socket information, manually defining io() just initializes the socket connection, even if within the Vue.use() function. Have you found a solution?

**Comment by sreecodeslayer** [comment]
> manually defining io() just initializes the socket connection

It does that, but nothing else

>Have you found a solution?  

I ended up using the socketio lib as such inside my components, not sure if that is gonna serve all my purpose. My application is still on its early stages. 

I am guessing that I might have issues with the events (`on`), since I have noticed that the `on` doesn't get triggered on each receive. It is only triggered when used as a promise to `emit`. This could be because I used the `emit` and `on` inside a normal `method`, instead, I might need to do it this way `sockets:{}`.

**Comment by notchris** [comment]
I was able to define my ws connection within the vue instance, and then attach methods to the ws events. It's a little weird, but I was able to build a basic chat example and differentiate message types (although, it's probably not the best method). Not sure if it will help but:

**Server:**
const express = require('express');
const app = express();
const WebSocket = require('ws');
const moment = require('moment')

app.set('view engine', 'ejs');
app.use(express.static(__dirname + '/public'));

app.get('/', (req, res) => {
	res.render('pages/index');
});

const wss = new WebSocket.Server({ port: 8080 });

let users = [];

wss.broadcast = function broadcast(data) {
  wss.clients.forEach(function each(client) {
    client.send(data);
  });
};

wss.on('connection', function connection(ws) {

  users.push({id: ws._ultron.id});
  wss.broadcast(JSON.stringify([0,users]))

  ws.on('message', function incoming(data) { 
  	wss.broadcast(JSON.stringify([1,ws._ultron.id,data,moment().format('h:mmA')]))
  });

  ws.on('close', function(){
  	for (let i = 0; i < users.length; i++){
  		if (users[i].id == ws._ultron.id){ users.splice(i,1) }
  	}
    wss.broadcast(JSON.stringify([0,users]))
  })

});

app.listen(5000, function() {
    console.log('Running on port 5000.')
});

**Client:**
`"use strict";
window.WebSocket = window.WebSocket || window.MozWebSocket;

let app = new Vue({
    el: '#app',
    data: {
    	height: window.innerHeight - 128,
    	connection: new WebSocket('ws://localhost:8080'),
    	messages: [],
        users: []
    },
    methods: {
    	message: function(){
    		if (this.$refs.message.value !== ''){
    			this.connection.send(this.$refs.message.value)
    			this.$refs.message.value = '';
    		}
    	},
    	clearMessages: function(){
    		this.messages = [];
    	}
    }
})

app.connection.onopen = function (data) {
	console.log(app.connection)
};

app.connection.onmessage = function (message) {
	let msg = JSON.parse(message.data);
	if (msg[0] == 0){
		app.users = msg[1]
	} else if(msg[0] == 1){
		app.messages.push({user: msg[1], message: msg[2], time: msg[3]})
		Vue.nextTick(function () {
			app.$refs.messages.scrollTop = app.$refs.messages.scrollHeight;
		})
	} else {
		console.log('Invalid message.');
	}
}

app.connection.onerror = function (error) {
    console.log('Error while connecting.');
};

window.onresize = function(event) {
	app.height = window.innerHeight - 128;
};`

**Comment by sreecodeslayer** [comment]
Any solution from anybody on this?
