### ISSUE TITLE
Uncaught TypeError: Cannot read property 'BlobBuilder' of undefined

### ISSUE THREAD

**Issue by Zenfeder** [MetinSeylan/Vue-Socket.io#11]
Hi, when I use vue-socket.io 2.0.0 in my project that is building by vue 2.0, an error occurred that **_Uncaught TypeError: Cannot read property 'BlobBuilder' of undefined_** in chrome console. I don't know why. Please help me. Q&A!

**Comment by MetinSeylan** [comment]
https://github.com/MetinSeylan/Vue-Socket.io/issues/12
