### ISSUE TITLE
Vuex integration: custom callbacks receive data as array

### ISSUE THREAD

**Issue by okas** [MetinSeylan/Vue-Socket.io#110]
I want to use Vuex integration.
I've noticed that `Observer.onEvent()` function passes data (payload, 2nd arg) as array to passToStore funtion:
`if(this.store) this.passToStore('SOCKET_'+packet.data[0],  [ ...packet.data.slice(1)])`

Few lines below where some socketio events are iterated data is passed without wrapping into array.
Socketio events that are iterated:
` ["connect", "error", "disconnect", "reconnect", "reconnect_attempt", "reconnecting", "reconnect_error", "reconnect_failed", "connect_error", "connect_timeout", "connecting", "ping", "pong"]`.
Inside loop: `if(_this.store) _this.passToStore('SOCKET_'+value, data)`

**Comment by felixheck** [comment]
what's the reason for wrapping it in an array?! If I need an array, I emit wrapped message..

**Comment by codeofsumit** [comment]
this just broke our production build. Definitely a breaking change wrapped in a patch-version-update

**Comment by grapewheel** [comment]
@adi-darachi thx, I got the confuse until find the issue, and research the code of this plugin, so be it!

**Comment by felixheck** [comment]
Hi @MetinSeylan, would you mind sharing the reasons for closing this issue?
Is there a new related release?

**Comment by jarvelov** [comment]
@MetinSeylan Any comment on this? Was really odd to find this happened when starting to use the plugin.
