### ISSUE TITLE
Error building project from vue-cli webpack

### ISSUE THREAD

**Issue by Garmichael** [MetinSeylan/Vue-Socket.io#12]
Hi there,

I used vue-cli to create the standard webpack scaffolding.

I'm using vue2 and vue-socket.io.

Running on the dev server, everything works perfectly. But when I build and run the built server, I get:

build.js:2Uncaught ReferenceError: f is not defined(…)

The problem isn't there when I don't include vue-socket.io (but then I can't use this awesome library)

**Comment by drozdzynski** [comment]
Hello,

I have the same problem, on dev build works, but on production build not work.
Laravel elixir + webpack + vuejs2

My console log: `app.js:54 Uncaught ReferenceError: c is not define`

**Comment by tomvdv** [comment]
@Garmichael update your UglifyJsPlugin configuration in `/build/webpack.prod.conf.js` to avoid mangling names, like so:

`
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      mangle: false
    }),
`

**Comment by Neewd** [comment]
Don't work for me :( 
Even in dev or prod.
