### ISSUE TITLE
Vue.mixin is called several times

### ISSUE THREAD

**Issue by qiulang** [MetinSeylan/Vue-Socket.io#120]
I found Vue.mixin is called several times although I only call Vue.use(...) once, and many times this.$options['sockets'] is undefined. I don't have a clue yet, how do I debug it ?

**Comment by probil** [comment]
It's because of dynamic socket listeners feature. Plugin adds mixin to all the components doesn't metter is have `this.$options.sockets` or not. It actually listens for `this.$options.sockets` change under the hood using Proxy API
