### ISSUE TITLE
Sharing same socket across multiple tabs

### ISSUE THREAD

**Issue by nabeelalis** [MetinSeylan/Vue-Socket.io#124]
Is there anyway to share single socket connection across multiple tabs?

**Comment by vdcrea** [comment]
On front end side no, every tab is a new socket. But your backend may share the user session with socket session, so it can send back to client a common information across multiple tabs.

**Comment by nabeelalis** [comment]
Got it.

**Comment by miladd3** [comment]
it can be done with shared web workers
