### ISSUE TITLE
[Question] Socket.IO & Cloudflare

### ISSUE THREAD

**Issue by creazy231** [MetinSeylan/Vue-Socket.io#127]
Hi @all
Im trying to run a website with socket.io and want to enable DDOS protection from cloudflare. As I know cloudflare supports websocket-servers such as socket.io.
After I enabled cloudflare successfully and changed the ports of my socket-connection, the google dev console tells me:

`Failed to load http://my-domain.com:2083/socket.io/?EIO=3&transport=polling&t=M9uD7PJ: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my-domain.com.com' is therefore not allowed access. The response had HTTP status code 400.`

Someone can tell me what I have to change?

PS: Im working with the vuejs-cli

**Comment by dobeerman** [comment]
@creazy231 did you resolve this issue?

**Comment by creazy231** [comment]
```
io.set('origins', 'http://my-domain.com:*');
```
was the code line make it work

hope that helps you

**Comment by dobeerman** [comment]
@creazy231 Is it right?

```js
import VueSocketio from 'vue-socket.io';

Vue.use(Vuetify);

VueSocketio.set('origins', 'http://localhost:8080:*');
Vue.use(VueSocketio, 'ws://echo.websocket.org/');
```

**Comment by creazy231** [comment]
@dobeerman no, you have to use ``io.set('origins', 'http://my-domain.com:*');`` on your serverside code.
