### ISSUE TITLE
Vuex integration failed

### ISSUE THREAD

**Issue by abnerwang0991** [MetinSeylan/Vue-Socket.io#128]
import VueSocketio from 'vue-socket.io'
Vue.use(VueSocketio, socketio('http://localhost:3000'), store);

console:
main.js?1c90:16 Uncaught ReferenceError: socketio is not defined
    at eval (main.js?1c90:16)
    at Object../src/main.js (app.js:3497)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.0 (app.js:3554)
    at __webpack_require__ (app.js:679)
    at app.js:725
    at app.js:728

if I use Vue.use(VueSocketio, 'http://localhost:3000', store);
the "socket_" prefix used in actions doesn't work.

"vue-socket.io": "^2.1.1-a",

**Comment by Finelai** [comment]
Same :(

**Comment by probil** [comment]
There correct flow is:
```js
import Vue from 'vue';
import VueSocketio from 'vue-socket.io';
import socketio from 'socket.io-client';
import store from './store';

Vue.use(VueSocketio, socketio('http://localhost:3000'), store);
```

**Comment by probil** [comment]
Thanks for good words @Patskimoto . Nice to hear :)

BTW, I develop forked version of `vue-socket.io` as [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended)
it has better docs, better support, unit test, `~70kb` smaller when using custom socket.io instance (your case) and many other features. Check it out [here](https://github.com/probil/vue-socket.io-extended)

**Comment by Patskimoto** [comment]
@probil Thanks for the heads up - definitely going to look into potentially using your fork for my project, much appreciated!

**Comment by jeystaats** [comment]
@probil nice one , great that someone has picked this up!
