### ISSUE TITLE
connect function dosen't console anything,but channel has working,why?

### ISSUE THREAD

**Issue by Tamn9208** [MetinSeylan/Vue-Socket.io#129]
```
sockets:{
        connect: function(){
          console.log('socket connected')
        },
 }
```
I can get imformation from socket ,but when i refresh the page,app can not  get the connection msg

**Comment by jakietwo** [comment]
I have the same issue , did u have resolve it?

**Comment by vallettea** [comment]
@MetinSeylan Why do you close these issues ? they seem unresolved, I have the same problem. Or if they are can you provide an explanation ?

**Comment by tsikah** [comment]
Same Issue @vallettea , did you manage to get a solution? Please advise
