### ISSUE TITLE
connect_error missed

### ISSUE THREAD

**Issue by dgpgdev** [MetinSeylan/Vue-Socket.io#13]
Hi, 
I don't see connect_error event on sources.

I propose to fix it with :

  ["connect", "error", "disconnect", "reconnect", "reconnect_attempt", "reconnecting", "reconnect_error", "reconnect_failed"]
            .forEach((value) => {
                _this.Socket.on(value, (data) => {
                    Emitter.emit(value, data)
                })
            })
            _this.Socket.io.on('connect_error', (error) => {
                Emitter.emit('connect_error', error)
            })

to listen connection error first time when we don't need to reconnect.

**Comment by MetinSeylan** [comment]
fixed
https://github.com/MetinSeylan/Vue-Socket.io/commit/b0df13186c899b5fdf6583d3dc514ce1786c4fa2
