### ISSUE TITLE
this.$socket not available?

### ISSUE THREAD

**Issue by gijo-varghese** [MetinSeylan/Vue-Socket.io#134]
I want to emit an even after connection, something like this (it's inside a `.vue` component):

```
<script>
export default {
  sockets: {
    connect: () => {
      this.$socket.emit("join_room", "abc");
    },
  }
};
</script>
```

But it doesn't work. 
 

> Cannot read property 'emit' of undefined

I've searched a lot in the docs and issues. Couldn't find a solution

Also is this library still maintained? Seems to have very poor docs

**Comment by probil** [comment]
Hi @gijo-varghese 
Your code should work.
And yes this library is not maintained well. The only way to merge PR is contacting the author via email.


But there is another way. I've forked the library as [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended)  and develop it with tests/CI/support, etc
Could please check is that issue exist in the fork? I'd like to help you. If Yes, please create an issue in the fork repo. 

Best regards,
 Max Lyashuk

**Comment by gijo-varghese** [comment]
@probil Awesome. I'll try that repo

The code wasn't working. I'd tested it. I had set `window.vm = new Vuer(...)` and them `vm.$socket.emit(...)`
