### ISSUE TITLE
HTTPS socket 

### ISSUE THREAD

**Issue by AX-NICOLAS** [MetinSeylan/Vue-Socket.io#135]
Hello,

How implement socket.io in HTTPS ?

Have you a sample in https, please ?

I try set my name domain on backoffice and on the backend port 443 but this not working.

Thanks

**Comment by DRoet** [comment]
I wasn't able to test this out but you should be able to just use https in the url like:

`Vue.use(VueSocketio, 'https://socketserver.com');`

Or pass the secure option to the socket.io-client

`Vue.use(VueSocketio, socketio('https://socketserver.com:1923', { secure: true }));`

You just have to make sure your socket server also runs over TLS correctly (valid certificate), but there should be plenty of examples of that online

**Comment by Shadomax** [comment]
Hello @MetinSeylan @AX-NICOLAS @DRoet . i have followed the example but my front-end is still not connecting to the io server.
server.js file

var app = require('express')();
var server = require('http').Server(app);
var allowedOrigins = "https://example.com:* http://example.com:*";
var io = require('socket.io')(server, { origins: allowedOrigins});
var redis = require('redis');

server.listen(8890, function() {
  console.log('Listening on Port 8890')
});

// create admin url namespace
const chat = io.of('/admin');

io.on('connection', function (socket) {
  chat.emit('counter', io.engine.clientsCount);
  console.log("new client connected");
  var redisClient = redis.createClient();
  var redisClient1 = redis.createClient();
  var redisClient2 = redis.createClient();
  var redisClient3 = redis.createClient();
//   var redisClient4 = redis.createClient();

  redisClient.subscribe('newAlert');
  redisClient.on("message", function(channel, notification) {
    console.log("new notification in queue: "+ notification);
    socket.emit(channel, notification);
    chat.emit(channel, notification);
  });

  redisClient1.subscribe('playlist');
  redisClient1.on("message", function (channel, notification) {
      console.log("new playlist notification in queue: " + notification);
      socket.emit(channel, notification);
      chat.emit(channel, notification);
  });

  redisClient2.subscribe('plays');
  redisClient2.on("message", function (channel, data) {
      console.log("new song play count in queue: " + data);
      socket.emit(channel, data);
  });

  redisClient3.subscribe('fans');
  redisClient3.on("message", function (channel, data) {
      console.log("new follower count in queue: " + data);
      socket.emit(channel, data);
    });

  socket.on('disconnect', function() {
    console.log(io.engine.clientsCount);
    chat.emit('counter', io.engine.clientsCount);
    redisClient.quit();
    redisClient1.quit();
    redisClient2.quit();
    redisClient3.quit();
  });

});

io.of('/admin').on('connection', function (socket) {
    console.log(io.engine.clientsCount);
    console.log("new admin client connected");
    var redisClient = redis.createClient();
    var redisClient1 = redis.createClient();
    var redisClient2 = redis.createClient();
    var redisClient3 = redis.createClient();
    // var redisClient4 = redis.createClient();

    redisClient.subscribe('notification');
    redisClient.on("message", function (channel, notification) {
        console.log("new notification in queue: " + notification);
        socket.emit(channel, notification);
    });

    redisClient1.subscribe('logger');
    redisClient1.on("message", function (channel, user) {
        console.log("user activity: " + user);
        socket.emit(channel, user);
    });

    redisClient2.subscribe('newDownloadRequest');
    redisClient2.on("message", function (channel, data) {
        console.log("new beat download request: " + data);
        socket.emit(channel, data);
    });

    redisClient3.subscribe('newOrder');
    redisClient3.on("message", function (channel, data) {
        console.log("new purchase order: " + data);
        socket.emit(channel, data);
    });

    socket.on('disconnect', function () {
        console.log(io.engine.clientsCount);
        redisClient.quit();
        redisClient1.quit();
        redisClient2.quit();
        redisClient3.quit();
    });

});


socket.io plugin

`Vue.use(VueSocketio, 'https://example.com:8890', { secure: true })`

Am using Digital Ocean for hosting, Laravel as API backend, NuxtJs as frontend client and redis with socket io plugin. Please what am i miss out here
