### ISSUE TITLE
Emit multiple times

### ISSUE THREAD

**Issue by xeroxstar** [MetinSeylan/Vue-Socket.io#136]
I got confused what i am doing wrong here:

> Here is my main.js code:

```
import app from './components/app';
import VueSocketio from 'vue-socket.io';
Vue.use(VueSocketio, 'http://192.168.0.191:8080/');

new Vue({
    render: h => h(app),
    sockets:{
        connect: function(){
            console.log('socket connected')
        },
    }

}).$start();
```

> here is my app.vue

```
export default {
        name: "App",
        methods:{
            emit:function(){
                this.$socket.emit('custome.event',{data:'hello world'});
            }
        },
        created:function(){

            this.$socket.on('custome.event',function(data){
               // console = 'hello world'
            })
        }
}
```
Every time i trigger emit function, the callback multiply. So it's go like this:

> first time i trigger   :   hello world
> second time trigger:  hello world 
>                                   hello world
> third time i trigger  : hello world
>                                   hello world
>                                  hello world

I am not sure where is the problem comming from? By the way i am using the vue nativescript, if any one have a solution?

Thx

**Comment by xeroxstar** [comment]
Nevermind, found the error. It was on the server side, i should be careful.

**Comment by KiritchoukC** [comment]
Hi @xeroxstar,

I've the same issue, how did you solve it ?

Thanks
