### ISSUE TITLE
Can i use multi namespace?

### ISSUE THREAD

**Issue by pouu69** [MetinSeylan/Vue-Socket.io#147]
I want to use multiple namespaces in a page or component.
So I want to send and receive different data by namepsace.
However, there is no description of such a function in this library.
Is it possible?

**Comment by lexmav** [comment]
I join the question!

**Comment by AndyChuang1** [comment]
I also want to know

**Comment by JoyCood** [comment]
i also want to know

**Comment by pouu69** [comment]
why did you close this issue?

**Comment by boriskogan81** [comment]
Same here.

**Comment by redcomethk** [comment]
I tried to google this and found this answer on SO:
https://stackoverflow.com/questions/54629494/dynamically-joining-rooms-in-vue-socketio

Seems room is actually a layer of abstraction to manage client on server, i.e. it does not exist on client...
And from the official socket io client API, I also cannot find the corresponding function for joining a room in client side.
So I think the way to join is like the answer in the SO link, join the room by emitting the corresponding event from the socket and let backend to join that socket to the needed room.
