### ISSUE TITLE
why the socketio was not found in my code

### ISSUE THREAD

**Issue by sparGuan** [MetinSeylan/Vue-Socket.io#148]
![image](https://user-images.githubusercontent.com/28480563/45475540-4adc3b00-b76f-11e8-8f5a-4fb05d96b31f.png)
![z hqdda54rw 5 kd ii](https://user-images.githubusercontent.com/28480563/45475560-562f6680-b76f-11e8-94cd-5b773607a2a5.png)
socketio is not find

**Comment by sparGuan** [comment]
I checked your code found that the socketio have to install the socket.io and io(xxxx)

**Comment by Peter2962** [comment]
I'm also getting this error.
