### ISSUE TITLE
How do I reconnect when this server breaks the link

### ISSUE THREAD

**Issue by xyydd** [MetinSeylan/Vue-Socket.io#149]
1. I send a field to the server and the server will disconnects
2. how do I reconnect to the server in the vue component

**Comment by DonPrus** [comment]
The same issue. Some times I've got `WebSocket is already in CLOSING or CLOSED state`, and than users should refresh there pages because they didn't get any new messages.

**Comment by xeroxstar** [comment]
**Here what worked for me:**

import VueSocketIo            from 'vue-socket.io';
import io                             from 'socket.io-client';

let ioInstance = io('https://domain.com',{
  'reconnection': true,'reconnectionDelay': 500,'maxReconnectionAttempts':Infinity
});

Vue.use(VueSocketIo, ioInstance);

> then you need to call **connect()** after you disconnect :

sockets: {
     disconnect() {
          ioInstance.connect()
     }
}

**Comment by davidheryanto** [comment]
My simple solution: Try reconnecting every x seconds, if current socket status is **disconnected**

```javascript
mounted() {
      // Try to reconnect every 1.5 s if disconnected
      setInterval(() => {
        if (!this.$socket.connected) {
          this.$socket.connect();
        }
      }, 1500)
    }
```
