### ISSUE TITLE
Usage with vue router

### ISSUE THREAD

**Issue by ainarend** [MetinSeylan/Vue-Socket.io#153]
Hello, first off thanks for the package.

Currently there seems to be a problem with vue router & vue socket.io implementation. My components are single file components.

If i do a redirect from one of my components using:
`this.$router.push({ name: 'home'  });`

Then in the responding component, the Vue instance's property 'sockets' is not called and the connect() or disconnect() methods are never called. Only when the client refreshes the page, the methods are fired like always.

I currently bypassed this issue by adding a not required prop on all components called connected and when i redirect i pass on the current state of socket connection:
`this.$router.push({ name: 'home', params: { connected: this.isConnected } });`

Now in the components mounted hook i check the prop and update the state handling data value accordingly. 

But in my eyes the sockets prop should be called also when a component is used by vue router.

**Comment by xzaz** [comment]
This is still a problem.

**Comment by wangfpp** [comment]
This is still a problem.
