### ISSUE TITLE
Android 4.4 (Coolpad)

### ISSUE THREAD

**Issue by zeroprofit** [MetinSeylan/Vue-Socket.io#154]
Hi,

I'm using an old android phone.   Android version 4.4.2, kernel 3.4.0 system6@ubuntu on Coolpad 5560S.

The line "new Map()" in ./src/Emitter.js is not supported and I am not able to use VueSocket in my cordova app.  socket.io-client works great.

I would love it if you could fix ./src/Emitter.js so I can get socket.io to work.  Thanks!

**Comment by LinusBorg** [comment]
You can include a polyfill for `Map` in your app.

**Comment by zeroprofit** [comment]
Thank you.   I use this line in my main.js file

import 'core-js'

It is working now.  Map is polyfill using core-js.
