### ISSUE TITLE
How i can receive `context ` from mutations?

### ISSUE THREAD

**Issue by itoonx** [MetinSeylan/Vue-Socket.io#157]
In my mutation:

```
SOCKET_BALANCE_CHANGES: (state, context, newBalance) => {
// do stuff
}
```

I want to using rootState from context but in vue-socketio not have provide

**Comment by LinusBorg** [comment]
That's because mutations don't have access to context in vuex. This has nothing to do with this library.

Use an action if you need to access the context.
