### ISSUE TITLE
How to correctly setup Vue-Socket.io with the official vue webpack-template

### ISSUE THREAD

**Issue by alexsinfarosa** [MetinSeylan/Vue-Socket.io#16]
Hi, I have never used socket.io. I am struggling with setting up Vue-Socket.io with the official Vue webpack template (working locally). I am getting the following errors in the console:

![image](https://cloud.githubusercontent.com/assets/7988626/20841668/a4aea340-b882-11e6-8289-8b35c7ee232e.png)

I am also using vue-router, I hope is not the cause of this problem.

The main.js file:

import Vue from 'vue';
import VueSocketio from 'vue-socket.io';

Vue.use(VueSocketio, 'http://http://localhost:4000/');  // Is this correct?

Thanks!

**Comment by MetinSeylan** [comment]
do you have a socket.io server?

**Comment by alexsinfarosa** [comment]
Oh! no idea. Never used socket.io. What should I do?

**Comment by MetinSeylan** [comment]
http://socket.io/docs/

this doc help for you
