### ISSUE TITLE
Multiple socket namespaces

### ISSUE THREAD

**Issue by viniciusrebel** [MetinSeylan/Vue-Socket.io#162]
Are there any plans to support multiple socket namespaces?

I made it work locally, but had to change the API. More specifically I had to transform "$socket"  into an Object, and the connection config into an Array. I kept the single namespace option as well.

Let me know if you want to take a look at it, I can open a PR then.

**Comment by MetinSeylan** [comment]
yes it's in roadmap, but you can open PR for us, if you want

**Comment by focux** [comment]
If this is not done yet, I would like to open a PR with this.
