### ISSUE TITLE
VueSocketIO is Not a Constructor

### ISSUE THREAD

**Issue by jacobedawson** [MetinSeylan/Vue-Socket.io#164]
Hi, thanks for making this module. 

I've added VueSocketIO ("vue-socket.io": "^2.1.1",) to my project (Vue 2 w/ Vue CLI 3) and I've added it in main.js using the first documented installation method: 

```
import Vue from 'vue'
import store from './store'
import App from './App.vue'
import VueSocketIO from 'vue-socket.io'
Vue.use(
  new VueSocketIO({
    debug: true,
    connection: "http://localhost:3000",
    vuex: {
      store,
      actionPrefix: "SOCKET_",
      mutationPrefix: "SOCKET_"
    }
  })
);
// other setup code...
```

However, doing that breaks my app and gives me the following error: 

Uncaught TypeError: vue_socket_io__WEBPACK_IMPORTED_MODULE_13___default.a is not a constructor

I'm not sure how it could be the case that it's not a constructor if it's instantiated with the new keyword - is there another way I should be integrating this into a Vue project?

**Comment by MetinSeylan** [comment]
Hello @jacobedawson
this example for ^3.0.0 version, if you want you can upgrade version to 3.0.0 for your project, also i will push old documentations for ^2.0.0
