### ISSUE TITLE
Unsupported connection type after webpack

### ISSUE THREAD

**Issue by nodegin** [MetinSeylan/Vue-Socket.io#166]
`connection.constructor.name` is not `'Socket'` anymore after minification

It become something single letter, this causing me unable to connect to server by connection object.

```js
const connection = io.connect(server, {
  transports: ['websocket'],
  upgrade: false,
})
Vue.use(new VueSocketIO({ connection }))
```

Please remove that checking and publish a new version ASAP please..
I am currently modified the lib in node_modules to get it runnable in production

**Comment by ethanbud5** [comment]
I'm not sure if I have the same issue but I'm getting the "Unsupported Connection Type" error when I try to serve my dist build with a node server.  This is the error I'm getting in the console: 
![image](https://user-images.githubusercontent.com/38892120/49903038-69fc6e80-fe2b-11e8-91c7-fd37f6e93f37.png)
Any help would be great!
