### ISSUE TITLE
How use Dynamic Listeners if use Vuex?

### ISSUE THREAD

**Issue by neonkaafi** [MetinSeylan/Vue-Socket.io#168]
Hello

How use Dynamic Listeners in app if use Vuex?

**main.js**
`Vue.use(new VueSocketIO({
  debug: true,
  connection: 'http://localhost:8888',
  vuex: {
    store,
    actionPrefix: 'socket_',
    mutationPrefix: 'SOCKET_'
  }
}))`

**App.js**
`created () {
this.sockets.subscribe('EVENT_NAME', (data) => {
    this.msg = data.message;
});
}`

**[Vue warn]: Error in created hook: "TypeError: this.sockets is undefined"**

If I use this.$socket, I see the same problem

**Comment by MetinSeylan** [comment]
hello @neonkaafi 
plugin mixin, using `created` method for setting variables, you need to use `beforeMount` or `mounted` hooks
