### ISSUE TITLE
[Improvements]Add possibility to have severals socket.io connections

### ISSUE THREAD

**Issue by throrin19** [MetinSeylan/Vue-Socket.io#17]
Hi,
It's possible to have multiple socket.io connections (for example on differents servers) ?
In my case, I work in a microservices architecture and some of them have a socket.io server.

With the current mode of your library, I can't use this for my projects.

Thanks

**Comment by MetinSeylan** [comment]
hi,
multiple connections instead work with namespace is best way?

**Comment by throrin19** [comment]
In my case, server urls are not the same. It's different than namespace
