### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by BossOfGames** [MetinSeylan/Vue-Socket.io#174]
**Describe the bug**
Happens on loading before completely mounting the Vue plugin.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 3.0.4

**Additional context**

```js
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store/index'
import VueSocketIO from 'vue-socket.io';

import io from 'socket.io-client';



Vue.config.productionTip = false;

// first, retrieve from any settings provided by the frame
let hash = window.location.hash;
let setting_string = hash.split('?');
let settings = getUriSettings(setting_string[1]);
console.log(settings);

const connection = io.connect('http://localhost:3000', { transports: ['websocket'], upgrade: false});

Vue.use(VueSocketIO, new VueSocketIO({connection, debug:true}));
console.log('Initializing Vue');
new Vue({
    router,
    store,
    sockets: {
        connect: function () {
            console.log('Connected. Sending Authentication');
            this.$socket.emit('authentication', {
                id: settings.token_id,
                userId: settings.user_id
            });
        },
        authenticated: function () {
            console.log('Authentication Complete');
            this.subscribeChannel();
        }
    },
    methods: {
        subscribeChannel()
        {
            this.$options.sockets.subscirbe(settings.frame_id, (msg) => {
                // We received data on the channel. We need to double check now what the server is requesting.
                // We need to first figure out what the server is sending. Check the object.
                switch (msg.scene) {
                    case 'miniboard':
                        store.commit('miniboard/set', msg.data);
                        break;
                    case 'bracket_rollout':
                        store.commit('bracket_rollout/set', msg.data);
                        break;
                }
            });
            console.log('Now Listening On Frame: ' + settings.frame_id);
        }
    },
    render: h => h(App)
}).$mount('#app');

function getUriSettings(uri)
{
    // after the ?, get the settings.
    let options = uri.split('&');
    let settings = [];
    // now, let's get the key/value pairs
    options.forEach((key) => {
        let a = key.split('=');
        settings[a[0]] = a[1];
    });
    return settings;
}
```

Stack trace provided by debugger:

```
Uncaught TypeError: Cannot call a class as a function
    at eval (vue-socketio.js?5132:10)
    at t (vue-socketio.js?5132:10)
    at Function.Vue.use (vue.runtime.esm.js?2b0e:4749)
    at eval (main.js?56d7:21)
    at Module../src/main.js (app.js:2768)
    at __webpack_require__ (app.js:768)
    at fn (app.js:131)
    at Object.0 (app.js:2853)
    at __webpack_require__ (app.js:768)
    at app.js:904
```

**Comment by MetinSeylan** [comment]
hi @BossOfGames 
can you try without `$options` like this -> this.sockets.subscirbe

**Comment by ranarn** [comment]
Without looking at the details of your code, but you have misspelled subscribe

this.$options.sockets.subscirbe(settings.frame_id, (msg) => {

**Comment by AlamTheInnov** [comment]
i have the same error.

**Comment by satriaajiputra** [comment]
This error can solve with this method, but I can't insert ``query`` to the **Vue-Socket.io** while connection. Anyone can solve this problem?

```js
Vue.use(new VueSocketIO({
    debug: true,
    connection: 'http://localhost:3000',
    query: {
        token: window.localStorage.getItem('auth')
    }
}));
```

**Comment by UchennaPrudensia** [comment]
Reinstall vue-socket.io to version 2.1.1-b
    npm install vue-socket.io@2.1.1-b --save 

The older version works. I am curios to know why. Please can someone look into it. Thank you!

**Comment by carlsunderman** [comment]
> npm install [vue-socket.io@2.1.1-b](mailto:vue-socket.io@2.1.1-b) --save

Can verify this fixes the issue on windows, Chrome as well

**Comment by sambrightman** [comment]
Still appears to be an issue on 3.x. Mis-spelling "subscribe" is not the cause, so I suggest re-opening this.

**Comment by m0bbin** [comment]
bump. Still an issue @carlsunderman answer helped for the meantime.

**Comment by RahulJadhav26** [comment]
> Reinstall vue-socket.io to version 2.1.1-b
> npm install [vue-socket.io@2.1.1-b](mailto:vue-socket.io@2.1.1-b) --save
> 
> The older version works. I am curios to know why. Please can someone look into it. Thank you!

Thank you this worked for me..!!

**Comment by olegruchovets** [comment]
Hi Guys, running the same issue. Linux mint chrome. It works after downgrading to  @2.1.1-b but it is already @3.x major release and issues still exist.
Can you please take look.

**Comment by Dream-cake** [comment]
Still happening

**Comment by Dream-cake** [comment]
issue has been found.
go to #286

**Comment by rochac2lee** [comment]
> This error can solve with this method, but I can't insert `query` to the **Vue-Socket.io** while connection. Anyone can solve this problem?
> 
> ```js
> Vue.use(new VueSocketIO({
>     debug: true,
>     connection: 'http://localhost:3000',
>     query: {
>         token: window.localStorage.getItem('auth')
>     }
> }));
> ```
> 
> **Update [SOLVED] :** Inserting query while connection can use method following the documentation
> 
> ```js
> const SocketInstance = socketio.connect('http://localhost:3000', {
>     query: {
>         token: window.localStorage.getItem('auth')
>     }
> });
> 
> Vue.use(new VueSocketIO({
>     debug: true,
>     connection: SocketInstance
> }));
> ```

Funcionou para mim! Obrigado!!!
