### ISSUE TITLE
Firefox error SyntaxError: missing : after property id after import

### ISSUE THREAD

**Issue by wvansl** [MetinSeylan/Vue-Socket.io#176]
**Describe the bug**
When using this in Chrome, it works fine, if I do it in FireFox I get the error:

> SyntaxError: missing : after property id

**Expected behavior**
It should work in Firefox also

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome works, Firefox not
 - Version: latest

**Additional context**

When I do:
**import VueSocketIO from 'vue-socket.io';**
I get in Firefox:
**SyntaxError: missing : after property id**

**Comment by SaadeMotion** [comment]
Syntax error its your fault, nothing related to the package itself.
Please paste some related code.
