### ISSUE TITLE
ERROR in build.js from UglifyJs

### ISSUE THREAD

**Issue by neonturk** [MetinSeylan/Vue-Socket.io#177]
Hi,
First of all thank you for this nice package.

I'm getting this error when I'm building my project.

`ERROR in build.js from UglifyJs
`
`Unexpected token: punc (() [./node_modules/vue-socket.io/dist/vue-socketio.js:8,32088][build.js:20487,32100]
`
`npm ERR! code ELIFECYCLE
npm ERR! errno 2`

Thank you from now..

**Comment by MetinSeylan** [comment]
selam @neonturk, 
webpack ayarların tam olarak nedir bilmiyorum ama konu ile alakalı şurada bir açıklama mevcut https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/205

**Comment by MetinSeylan** [comment]
paketten pakete değişebilir şunu inceleyebilirmisin https://github.com/leocornus/leocornus-vue-sandbox/commit/2d77e3b7563c7ec3b18a7720f9c5b143c44659d2

**Comment by neonturk** [comment]
Bende tam https://github.com/webpack/webpack/issues/5858#issuecomment-338430720 bunu paylaşacaktım. 
Aynı yöntem ile çözülüyor. Sanırım uglifyjs-webpack-plugin den kaynaklı sorunmuş. Fixlenmiş sürümü de beta olduğu için webpack henüz dahil etmemiş.
