### ISSUE TITLE
Can't acess methods from sockets

### ISSUE THREAD

**Issue by guiconti** [MetinSeylan/Vue-Socket.io#178]
**Describe the bug**
When a socket event is called i can't access my methods functions inside the sockets{} method.

**Expected behavior**
Use .this like i do in computed, methods, etc

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 43

**Additional context**
Example:

```
sockets: {
    newMessage: message => {
      this.sendMessage(message);
    }
  },
methods: {
    sendMessage(message) {
      console.log(message);
    }
  }
```

When i use this code i receive that this.sendMessage is not a function. Inspecting this. i can see that it is not properly referencing my component. Is there a way to fix this?

Thanks!

**Comment by MetinSeylan** [comment]
hi @guiconti 
can you change like this -> 
`
sockets: {
    newMessage: function(message) {
      this.sendMessage(message);
    }
  }
`
