### ISSUE TITLE
Uncaught TypeError: Cannot read property 'BlobBuilder' of undefined

### ISSUE THREAD

**Issue by Neewd** [MetinSeylan/Vue-Socket.io#18]
Hey,

Yes I know, that is the exact same problem that other issues but I tried to fix it with the uglify.mangle options but that doesn't work. 

So, I use socket.io on my Express server and I try to use Vue-socket.io in my app.js like this

import VueSocketio from 'vue-socket.io';

Vue.use(VueSocketio, 'http://socketserver.com:3000'); // i'm listening on port 3000 

new Vue ({
    sockets : {
           connect : function() {
                      console.log('connected to iosocket');
           }
    }
})

But when I webpack my project I've the error property blobuilder of undefined. 
Does Vue-Socket.io need any dependencies in blob ?

**Comment by MetinSeylan** [comment]
https://github.com/MetinSeylan/Vue-Socket.io/issues/12

**Comment by Neewd** [comment]
"Yes I know, that is the exact same problem that other issues but I tried to fix it with the uglify.mangle options but that doesn't work." 

What is not clear enough ? 
I already see this issue, and I already tried the uglify mangle options fix but that doesn't work !
