### ISSUE TITLE
Vuex error handler has empty data

### ISSUE THREAD

**Issue by NomNes** [MetinSeylan/Vue-Socket.io#180]
In Vuex, the `SOCKET_error` action does not contain a message.
```
export const actions = {
    SOCKET_error: ({}, data) => console.log(data), // data = undefined
    // BUT!
   SOCKET_any_other_event: ({}, data) => console.log(data) // data = {...}, its ok
}
```

In component `this.$socket.on("error", console.log)` works ok,  receive an error message

Maybe, change `src/listenler.js:41`:
From `VueSocketIOListenler.staticEvents.forEach(event => this.io.on(event, () => this.onEvent(event)))`
To `VueSocketIOListenler.staticEvents.forEach(event => this.io.on(event, args => this.onEvent(event, args)))`

**Comment by MetinSeylan** [comment]
@NomNes thank you for pr!
