### ISSUE TITLE
Stop polling request

### ISSUE THREAD

**Issue by charlysnife** [MetinSeylan/Vue-Socket.io#186]
Please where can i set vue-socket.io to be making only websocket request to server. As it is now, each time my websocket connects. It is keeps making polling request to the server.

**Comment by MetinSeylan** [comment]
you can pass custom socket.io-client instance to `connection` parameter

**Comment by cranx** [comment]
You can just add `transports: ['websocket', 'polling']` (default order is `['polling', 'websocket']`) to socket.io client options, like this:

```
   new VueSocketIO({
    debug: true,
    connection: 'http://metinseylan.com:1992',
    vuex: {
        store,
        actionPrefix: 'SOCKET_',
        mutationPrefix: 'SOCKET_'
    },
    options: { 
        path: "/my-app/", 
        transports: ['websocket', 'polling']  // <-- here
     } 
})
```
