### ISSUE TITLE
Using in nuxt with specific port number

### ISSUE THREAD

**Issue by aponxi** [MetinSeylan/Vue-Socket.io#187]
Hello,

Can you please give some information about how to use it with Nuxt with a specific port number? Where does the configuration go if I'm using vue-socket.io as a component?

Thanks in advance.

**Comment by Renari** [comment]
It's in the readme.
`    connection: 'http://metinseylan.com:1992',`
1992 is your port

**Comment by aponxi** [comment]
Thanks
