### ISSUE TITLE
能不能挂在bootcdn上？体积有点大

### ISSUE THREAD

**Issue by dxy2233** [MetinSeylan/Vue-Socket.io#190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MetinSeylan** [comment]
english please :(

**Comment by douira** [comment]
Google translate says the translation is "Can you hang on bootcdn? a bit big". I guess the person wanted you to add this package to bootcdn, which seems to be an entirely chinese CDN for bootstrap and other things... https://www.bootcdn.cn/ 
aha.

**Comment by dxy2233** [comment]
> Google translate says the translation is "Can you hang on bootcdn? a bit big". I guess the person wanted you to add this package to bootcdn, which seems to be an entirely chinese CDN for bootstrap and other things... https://www.bootcdn.cn/
> aha.

yes！
I have re-submitted the issues in English.
Forgive me for not being good at English.
