### ISSUE TITLE
webpack package error

### ISSUE THREAD

**Issue by zgs1108** [MetinSeylan/Vue-Socket.io#192]
Webpack package error， "Unexpected token: punc (() [./node_modules/vue-socket.io/dist/vue-socketio.js". In order to solve the packaging problem, add “resolve('/node_modules/vue-socket.io/dist/vue-socketio.js') ” in webpack.base.conf.js. Cause error “export 'default' (imported as 'VueSocketIO') was not found in 'vue-socket.io'” . I don't understand what caused this error, Is there any good solution?Thank you

**Comment by Kirill-Vorobyev** [comment]
Having the same error when running `npm run build` on a vue cli webpack-simple project after importing vue-socket.io
