### ISSUE TITLE
An error was reported in Internet explorer

### ISSUE THREAD

**Issue by hbb520** [MetinSeylan/Vue-Socket.io#194]
**Describe the bug**
An error was reported in Internet explorer.

When "import VueSocketIO from 'vue-socket.io'", The error message is "SCRIPT1003: 缺少 ':'"

**Expected behavior**
normal operation.

**Desktop (please complete the following information):**
 - Browser [Internet ,IE]
 - Version [^3.0.4]

**Additional context**

**Comment by hbb520** [comment]
ask for help

**Comment by MetinSeylan** [comment]
we are not supporting legacy platforms :(
