### ISSUE TITLE
how do i use room and namespace in vue-socket.io

### ISSUE THREAD

**Issue by izcream** [MetinSeylan/Vue-Socket.io#2]
i try to use `this.$socket.to(roomId).emit('sendchat_msg', data)` but  console.log tell this msg

Uncaught TypeError: this.$socket.to is not a function

how do i use it 

ps. sry for my bad english

**Comment by MetinSeylan** [comment]
Hi izcream

This is server side feature, not supported socket.io-client

**Comment by julesjanssen** [comment]
To use namespaces, just inject a namespaced socket instance into the `Vue.use` method directly, like:

```
import VueSocketio from 'vue-socket.io';

var io = require('socket.io-client');
var socket = io('localhost:8888/namespace');

Vue.use(VueSocketio, socket);
```

**Comment by TheAnosmic** [comment]
using namespace like this:
`var socket = io('localhost:8888/namespace');
Vue.use(VueSocketio, socket);`
will only listen to one room.
can rooms be added or removed in runtime?

**Comment by qmShen** [comment]
What if I cannot visit the server port directly? I have mapped the port to a subfolder. Can I write as: "Vue.use(VueSocketio, 'http://serverip/subfolder/namespace')"? Seem doesn't work.... TT

**Comment by ashx404** [comment]
I have the same question, how to implement a functionality like a room creation where user have to join on the basis of a roomID or something. All I find is how it can be used in any component of the app.
