### ISSUE TITLE
Register custom events dynamically

### ISSUE THREAD

**Issue by pinguinjkeke** [MetinSeylan/Vue-Socket.io#20]
Hi! I'm trying to register custom events dynamically.
Example
```
const entity = isAdmin ? 'administrator' : 'user'

this.$socket.on(`${entity}Online`, () => ....)
```

1. Component's "socket" section processes on beforeCreate method, where props data, computed are not available yet.
2. I can't register my events directly on Emitter class because of it's not a singleton.
3. I can't register any event on this.$socket instance because of  Observer's class this.Socket.onevent removes standard socket io behavior.

Some ways to solve the issue:
1. Make Emitter class singleton:
```
// ... emitter class definition
const emitter = new Emitter

export default emitter
```
Than I can import it in my code
```
import Emitter from 'vue-socket.io/src/Emitter'

Emitter.addListener...
```

2. Set a fallback to socketIo's onevent to standard behaviour.
https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.js#L7868

BTW, I can make pull request

**Comment by michgeek** [comment]
I also run into the issue and I though I would use this solution:

```javascript
// Socket.js
import Client from 'socket.io-client'

const Socket = new Client('...');

export default Socket
```

```javascript
// App.js
import Vue from 'vue';
import VueSocketIO from 'vue-socket.io';
import Socket from 'socket'; // Singleton

Socket.on('myevent', function() { ... }); // Custom event

Vue.use(VueSocketIO, Socket); // This accepts also a Socket instance
```

`myevent` will not be triggered because the original `onevent` is overwritten
https://github.com/MetinSeylan/Vue-Socket.io/blob/master/src/Observer.js#L19

So yeah it would be nice to still benefit from the original `onevent`.

**Comment by pinguinjkeke** [comment]
@michgeek Singletone Emitter class will resolve an issue. Or you are want to use standard socket.io behavior?

**Comment by michgeek** [comment]
@pinguinjkeke I want to be able to use my own `Socket` instance because I am sharing it across the app in other services that are not a `Vue` instance.

**Comment by MetinSeylan** [comment]
new version
https://github.com/MetinSeylan/Vue-Socket.io/commit/8e0100be091c346115a019386cf18cdc527aa675
