### ISSUE TITLE
VUEX action not triggering.

### ISSUE THREAD

**Issue by yabuking84** [MetinSeylan/Vue-Socket.io#201]
Im not sure how the VUEX action name convention here.  I have been testing camelCase and the VUEX action is not triggering. Maybe if you can give me an example on how to create a VUEX action.  

Also why is actionPrefix all uppercase and on your old docs you put lowercase on action naming?
`Vue.use(new VueSocketIO({
    debug: true,
    connection: SocketInstance,
    vuex: {
        store,
        actionPrefix: 'SOCKET_',
        mutationPrefix: 'SOCKET_',
    },    
}));`

Also I made sure that my Node.js Socket.IO is emitting the event. Its working on components but on VUEX its not. So it maybe something on the VUEX. Maybe I miss something on the action naming convention. Maybe you can give a detailed example.

Thank you!

**Comment by evanbechtol** [comment]
Hey @yabuking84 Here is a quick example of how I was able to get mine up and running:

In your `main.js`, initialize your socket connection (doesn't have to be exactly like this, but this is how I set mine up):
```javascript
// In main.js
const options = { path: process.env.VUE_APP_SOCKET_PATH };

const uri = process.env.NODE_ENV === "production"
        ? process.env.VUE_APP_URL
        : process.env.VUE_APP_API_BASE;

const settings = {
  debug: false,
  connection: SocketIO(
    uri,
    options
  ),
  vuex: {
    store,
    actionPrefix: "SOCKET_",
    mutationPrefix: "SOCKET_"
  }
};

Vue.use(new VueSocketIO(settings));
```

Then, you can setup your VueX store/module I modularize my store to keep it clean):
```javascript
// In store.js
import Vue from "vue";
import Vuex from "vuex";
import socketModule from "./modules/socketModule";

Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    socketModule
  },
```

Finally, here is what the store module looks like ( `socketModule.js`):
```javascript
// In socketModule.js
export default {
  state: {
    isConnected: false,
    socketMessage: ""
  },
  mutations: {
    isConnected: function(state, payload) {
      state.isConnected = payload;
    },
    SOCKET_CONNECT(state) {
      state.isConnected = true;
    },
    SOCKET_DISCONNECT(state) {
      state.isConnected = false;
    },
    SOCKET_REFRESH_ITEM(state, payload) {
      state.selectedCord = payload;
    },
    socketMessage: function(state, payload) {
      state.socketMessage = payload;
    }
  },
  actions: {},
  getters: {}
};
```

I also created a mixin, which is used in my components and views. This makes for some really nice and reusable code:
```javascript
// In socketMixin.js
export const socketMixin = {
  sockets: {
    connect: function() {
      // Update the store variable "isConnected" to true
      this.$store.commit("SOCKET_CONNECT");
    },
    disconnect: function() {
      // Update the store variable "isConnected" to false
      this.$store.commit("SOCKET_DISCONNECT");
    },
    SOCKET_NOTIFY: function(data) {
      this.$store.commit("cordPullNotification", true);
      this.$store.commit("cordPullMessage", data);
      this.$store.commit("notificationLink", `/cord/${data.data._id}`);
    },
    SOCKET_REFRESH_DISCUSSION: function() {},
    SOCKET_REFRESH_GRID_ALL: function(data) {
      this.$store.commit("gridItems", data);
    },
    SOCKET_REFRESH_GRID_ONE: function(data) {
      this.$store.commit("gridItems", data);
    },
    SOCKET_REFRESH_ITEM: function(data) {
      this.$store.commit("selectedCord", data);
    },
    SOCKET_REFRESH_ERROR: function(data) {
      this.$store.commit("alert", true);
      this.$store.commit("alertMessage", data);
      this.$store.commit("alertColor", "#DC2D37");
      this.$store.commit("alertTimeout", 0);
    }
  },
  methods: {
    joinSelectedCordRoom: function(_id) {
      this.$socket.emit("JOIN_ITEM_ROOM", _id);
    },
    leaveSelectedCordRoom: function(_id) {
      this.$socket.emit("LEAVE_ITEM_ROOM", _id);
    },
    notify: function(data) {
      this.$socket.emit("NOTIFY", data);
    },
    refreshGrid: function() {
      this.$socket.emit("REFRESH_GRID_ALL", { query: { status: "Open" } });
    },
    refreshGridOne: function() {
      this.$socket.emit("REFRESH_GRID_ONE", { query: { status: "Open" } });
    },
    refreshItem: function(_id) {
      this.$socket.emit("REFRESH_ITEM", _id);
    }
  }
};
```

**Comment by yabuking84** [comment]
Thank You @evanbechtol for the reply. 

I was hoping that no socket listeners are on the component. I only have the VUEX action SOCKET_SUPPLIER_NEW_QUOTE_CREATED as my socket listener. Lets say all Socket related stuff are all in the VUEX. 

Here is my main,js:


   	import io from "socket.io-client";
	import VueSocketIO from "vue-socket.io";
	const SocketInstance = io("http://192.168.1.202:4113");
	Vue.use(new VueSocketIO({
	    debug: true,
	    connection: SocketInstance,
	    vuex: {
	        store,
	        actionPrefix: "SOCKET_",
	        mutationPrefix: "SOCKET_",
	    },    
	}));
    ...


Then my VUEX has a module BuyerInquiry.js:


	import axios from 'axios';
	import router from '@/router'
	import config from '@/config/index'

	const state = {
	    isConnected: false,
	    notifications: [],
	}

	const mutations = {
	    SOCKET_CONNECT(state) {
	      state.isConnected = true;
	    },

	    SOCKET_DISCONNECT(state) {
	      state.isConnected = false;
	    },

	    UPDATE_NOTIFICATIONS_M(state, data) {
	        state.notifications.push({
	            title: "test",
	        });
	    }
	}

	const actions = {
	    SOCKET_SUPPLIER_NEW_QUOTE_CREATED(context, data) {
	        context.commit('UPDATE_NOTIFICATIONS_M',data);
	    },
	}

	export default {
		namespaced: true,
		state,
		getters,
		mutations,
		actions	
	}





then on TestComponent.vue:


	<template>
	<h1>{{ notifcations }}</h2>
	</template>

	<script>
	...
	methods: {
	    triggerTestEvent() {
	        this.$socket.emit('supplierNewQuoteCreated', {inq_id:this.inquiry.id});
	    },
	},

	computed: {
	    notifications(){
	        return this.$store.state.notifications;
	    },
	},
	...
	</script>


As you can see on my component I dont have any Socket listeners. 

When triggerTestEvent() is triggered then  this.$socket.emit('supplierNewQuoteCreated', {inq_id:this.inquiry.id}); will also then trigger, but VUEX $state.notifications updates are not updating. 

I am sure that my Socket.IO server is triggering and emitting the supplierNewQuoteCreated event because I did some console.log() on those.

And Im sure that its not the Socket.IO because if I tested and added socket listeners to TestComponent.vue:


	sockets: {
	    supplierNewQuoteCreated: function() {
	        context.commit('UPDATE_NOTIFICATIONS_M',data);
	    },
	}


VUEX $state.notifications updates are working.

I was hoping that all my socket related stuff would only be in my VUEX modules. and in order to do that I need to make VUEX sockets work. but for me its not working.

Just to sum it all. I just want my VUEX sockets to work. It would be nicee if only VUEX action is used.

Thank you so much!

**Comment by yabuking84** [comment]
I made it work. 

on my VUEX BuyerInquiry.js:

	actions: {
		...
	    // supplierNewQuoteCreated
	    SOCKET_supplierNewQuoteCreated(context, data){
	        context.commit('UPDATE_NOTIFICATIONS_M',data);        
	    },
	    ...
	}


so it was just my naming convention on the actions.  before it was SOCKET_SUPPLIER_NEW_QUOTE_CREATED then renamed it to SOCKET_supplierNewQuoteCreated. Not it works!!

Thank you!

**Comment by evanbechtol** [comment]
@yabuking84 Be sure to close your issue if you have resolved it! Glad that you got it working :)

**Comment by yabuking84** [comment]
Thanks @evanbechtol! Yes it would be beneficial. or an example would be better. Ill propose something. Thank you again for your help!
