### ISSUE TITLE
Can you include example project ?

### ISSUE THREAD

**Issue by whaleforever** [MetinSeylan/Vue-Socket.io#205]
Hi,

I am still new with this vuesocket.io, I tried using the readme and yet I cannot use it, I can connect but still cannot grasp the understanding using vuex. 
so can you add the example project especially for the vue part?

thanks

**Comment by evanbechtol** [comment]
Hey there @whaleforever ! Someone else recently asked a similar question in issue #201 
Can you check that out and see if it helps put you in the right direction? I do agree that having a working example would help. Once I get some free time, I could set this up :)
