### ISSUE TITLE
Allow Mutations and Actions without prefix

### ISSUE THREAD

**Issue by kilobyte2007** [MetinSeylan/Vue-Socket.io#206]
In my project, It would really be handy to allow naked Mutations and Actions to be sent to the client so I don't have to have a lot of duplicate code. 
So if I have a mutation UPDATE_USER in vuex, I would only have to emit a UPDATE_USER event from the backend.

Is there a reason why this was done to only be work with some kind of prefix? If no I was thinking about creating a pull-request implementing this change.

**Comment by evanbechtol** [comment]
It might be a good idea to implement an option that allows toggling usage of prefix, that way it maintains backwards compatibility for those who upgrade their version, but are using prefixes. I'm really not sure of why the prefix was implemented, maybe @MetinSeylan Would be able to answer that one.

**Comment by Nisthar** [comment]
@evanbechtol vuex store events are not working for me. is this repo unmaintained?

**Comment by evanbechtol** [comment]
Hey @Nisthar 

Can you describe the issue you are facing? If you can, please share some code, expected behavior, actual behavior, test data, as much as possible to help out!

**Comment by Nisthar** [comment]
@evanbechtol Thanks. This is my code

`website/store/index.js` 
```js
import Vue from "vue";
import Vuex from 'vuex';
import actions from './actions';
import mutations from './mutations';

Vue.use(Vuex);

const store = new Vuex.Store({
    state: {
        isLoading: false,
        user: {},
        userType: ''
    },
    getters: {
        user: state => state.user,
        userType: state => state.userType
    },
    actions,
    mutations
});

export default store;
```

`website/global.js`
```js
import Vue from "vue";
import VueSocketIO from 'vue-socket.io';
import VueIziToast from "vue-izitoast";
import Vuetify, {
	VApp
} from 'vuetify/lib'
import {
	Ripple
} from 'vuetify/lib/directives';
import '@fortawesome/fontawesome-free/css/all.css'
import store from "./store";

Vue.use(new VueSocketIO({
	debug: true,
	connection: "http://localhost:3000",
	vuex: {
		store,
		actionPrefix: 'SOCKET_',
		mutationPrefix: 'SOCKET_'
	}
}));

const defaultOptionsObject = {
	theme: "dark",
	icon: "icon-bell",
	position: "topRight",
	progressBarColor: "rgb(0, 255, 184)",
};

Vue.use(Vuetify, {
	iconfont: 'mdi',
	iconfont: 'fa',
	components: {
		VApp
	},
	directives: {
		Ripple
	}
})

Vue.use(VueIziToast, defaultOptionsObject);
```

`website/store/actions.js`
```js
import axios from 'axios';
const actions = {
    async login({ context, commit, state, dispatch }, payload) {
        commit('SET_LOADING', true);
        const req = await axios.post("/login", payload);
        const res = req.data;
        this._vm.$toast.show(res.msg, res.status);
        commit('setLoading', false);
        console.log(res);
        if (res.data && res.data.user_email) {
       
          commit('SET_STATE', { key: 'user', data: res.data });
        }
        if (res.redirect) {
          setTimeout(() => {
            window.location.href = res.redirect;
          }, 3000);
        }
    },
    "SOCKET_FGG"({context, commit, state}){
      console.log(context);
      console.log('testing--------------------')
    }
}

export default actions;
```

`website/store/mutations.js`
```js
const mutations = {
    SET_LOADING(state, data) {
        state.isLoading = data;
    },
    SET_STATE(state, payload) {
        state[payload.key] = payload.data;
    },
    "SOCKET_SDF"(state, payload) {
        console.log(state);
    }
}

export default mutations;
```

This is my backend expressjs route used for emitting the events
`server/index.js`
```js
...
app.get("/api/test2", async (req, res) => {
	Socket.emit("SOCKET_SDF", { data: "testing" });
	Socket.emit("SOCKET_FGG", { data: "testing" });
	return res.json("done");
});
...
```
I loaded the client views and hit the api using a new tab. The store events doesn't work at all.

**Comment by Nisthar** [comment]
@evanbechtol I fixed the issue myself. The issue was using the prefix when emitting events.
 I had to read the source code to understand the proper usage. Thanks.

**Comment by kilobyte2007** [comment]
> Actually the prefix is optional, if you double-check the readme you'll see that you don't have to provide it :)

Yes, but if you don't provide a prefix, it is going to prepend it automatically. That's the issue I was raising.

**Comment by oz-** [comment]
@Nisthar I'm in the same situation: I don't understand how to use these prefixes.
Could you explain how it might be implemented? 
Thank you.

**Comment by probil** [comment]
@kilobyte2007 @oz- You can disable prefixes in [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended#gear-configuration)
