### ISSUE TITLE
vue-socketio.js?5132:8 GET /socket.io/?EIO=3&transport=polling&t=Meg-OLx 404 (Not Found)

### ISSUE THREAD

**Issue by brlafreniere** [MetinSeylan/Vue-Socket.io#208]
Getting a lot of these errors, some help or direction would be appreciated, thanks.

**Comment by briancaffey** [comment]
I'm seeing the same issue when trying to make this work with Django Channels.

**Comment by YuqiaoS** [comment]
You guys should specify what stack you are using so others can help. 404 means request to server can’t find matching address to give back responses.

**Comment by sabuhish** [comment]
@brlafreniere @MetinSeylan @briancaffey Hi there!
This issue has been closed, but unfortunately  I am still getting errors. I guess if it is closed that means problem solved already could you please give me some hints as well?any solution to occurred problem

I am using django-cahnnels to let vue.js connect to my socket. But unfortunately front-end developer faces issue some sort of cors errors and other socket  disconnections.
attaching photos just in case might help to figure out:

version socket.io used here:  "vue-socket.io": "^2.1.1-b",

<img width="1440" alt="Screen Shot 2019-07-19 at 11 27 37 AM" src="https://user-images.githubusercontent.com/46589585/61517623-c30f2f00-aa18-11e9-8b1f-849b7cca9afd.png">
<img width="743" alt="Screen Shot 2019-07-19 at 11 28 12 AM" src="https://user-images.githubusercontent.com/46589585/61517625-c3a7c580-aa18-11e9-9188-81f77a912d40.png">
<img width="555" alt="Screen Shot 2019-07-19 at 11 28 47 AM" src="https://user-images.githubusercontent.com/46589585/61517628-c3a7c580-aa18-11e9-8331-497abf5718fa.png">
<img width="1217" alt="Screen Shot 2019-07-19 at 11 30 12 AM" src="https://user-images.githubusercontent.com/46589585/61517629-c4405c00-aa18-11e9-82f2-1d1e923ca113.png">


fyi @peanutcoderr

**Comment by goors** [comment]
@sabuhish same here. did you ever resolve this?

**Comment by liquidvisual** [comment]
Why was this closed? How did you solve this @goors ??

**Comment by marlin-dev** [comment]
> @sabuhish same here. did you ever resolve this?

I think i installed cors library for django and setting it up helped me.
