### ISSUE TITLE
How to create 2 sockets for 2 different domain

### ISSUE THREAD

**Issue by henrytom1703** [MetinSeylan/Vue-Socket.io#214]
Domain 1: http://192.168.1.200:5000 (Socket.io)
Domain 2: ws://localhost:8093 (based on JSON RPC of Websocket protocol)
How to create and use sockets of 2 domains?
Ex: 
Vue.$socket.domain1.emit
Vue.$socket.domain2.emit

Thanks,

**Comment by MetinSeylan** [comment]
not yet, but in our roadmap

**Comment by Amaurgit** [comment]
Pleaaaaase implement this feature 🙏
