### ISSUE TITLE
enable socket per route

### ISSUE THREAD

**Issue by moeinrahimi** [MetinSeylan/Vue-Socket.io#215]
hi
by default socket io is enabled in every route which doesn't seem to be ok is there any way to enable socket only for routes that need access to socketio ?
thanks in advance

**Comment by W4G1** [comment]
Do you mean something like this?
```html
<!-- Inside a component -->
<script>
export default {
  sockets: {
    eventName (data) {
      // Only listens to this event when the component is rendered
    }
  }
}
</script>
```

You can listen to events on component level, so when the component is not created/rendered, it doesn't listen to it.

**Comment by brute-force** [comment]
mount in your router routes or in components using navigation guards (https://router.vuejs.org/guide/advanced/navigation-guards.html), not in main.js:
```
const router = new Router({
  routes: [
    {
      path: '/chat',
      name: 'chat',
      component: Chat,
      doAuthenticate: true,
      beforeEnter (to, from, next) {
        if (!Vue.prototype.$socket) {
          Vue.use(new VueSocketIO({
            connection: process.env.VUE_APP_WEBSOCKET_SERVER_URI
          }));
        }

        next();
      }
    }
....
```
