### ISSUE TITLE
useConnectionNamespace isn't an option of Vuex (documentation mistake)

### ISSUE THREAD

**Issue by strunkie30** [MetinSeylan/Vue-Socket.io#216]
**Describe the bug**
useConnectionNamespace isn't an option of Vuex, you can assign it only to the global option object.

**Expected behavior**
useConnectionNamespace is documented as global option.

**Additional context**
this one works:
````javascript
Vue.use(new VueSocketIO({
    debug: true,
    connection: 'http://localhost:3000/overview',
    vuex: {
        store,
    },
    options: {
        useConnectionNamespace: true
    },
}));
````

This one doesn't works:
````javascript
Vue.use(new VueSocketIO({
    debug: true,
    connection: 'http://localhost:3000/overview',
    vuex: {
        store,
        options: {
            useConnectionNamespace: true
        },
    },
}));
````

**Comment by Stonewon** [comment]
@strunkie30 is right! According to [index.js,](https://github.com/MetinSeylan/Vue-Socket.io/blob/caf4f56b106ffc3068f9aca3cb193137170e0241/index.d.ts) there is indeed documentation mistake. 'namespaceName' is also an option, thus the [index.d.ts](https://github.com/MetinSeylan/Vue-Socket.io/blob/8988085bef6bbf9ecdb5fced6b4220d5eb853bd3/src/index.js) should also be modified accordingly:
`
type MultiSockets = {
    [key: string]: SocketIOClient.Socket
}

declare module 'vue/types/vue' {
    interface Vue {
        $socket: SocketIOClient.Socket | MultiSockets, // modification 1
        sockets: {
            subscribe(eventName: string, handler: socketHandler<Vue>): void,
            unsubscribe(eventName: string): void,
        }
    }

declare module 'vue-socket.io' {
    import { PluginFunction, PluginObject } from 'vue'
    import { Store } from 'vuex'

    export interface VueSocketOptions {
        debug?: boolean;
        connection: string | SocketIOClient.Socket,
        vuex?: {
            store?: Store<any>,
            actionPrefix?: string,
            mutationPrefix?: string
        },
        options?: {
            useConnectionNamespace?: boolean,
            namespaceName?: string // modification 2
        }
    }
`

**Comment by Stonewon** [comment]
@strunkie30 is right! According to [index.js,](https://github.com/MetinSeylan/Vue-Socket.io/blob/caf4f56b106ffc3068f9aca3cb193137170e0241/index.d.ts) there is indeed documentation mistake. 'namespaceName' is also an option, thus the [index.d.ts](https://github.com/MetinSeylan/Vue-Socket.io/blob/8988085bef6bbf9ecdb5fced6b4220d5eb853bd3/src/index.js) should also be modified accordingly:
`type MultiSockets = {
    [key: string]: SocketIOClient.Socket
}

declare module 'vue/types/vue' {
    interface Vue {
        $socket: SocketIOClient.Socket | MultiSockets, // modification 1
        sockets: {
            subscribe(eventName: string, handler: socketHandler<Vue>): void,
            unsubscribe(eventName: string): void,
        }
    }

declare module 'vue-socket.io' {
    import { PluginFunction, PluginObject } from 'vue'
    import { Store } from 'vuex'

    export interface VueSocketOptions {
        debug?: boolean;
        connection: string | SocketIOClient.Socket,
        vuex?: {
            store?: Store<any>,
            actionPrefix?: string,
            mutationPrefix?: string
        },
        options?: {
            useConnectionNamespace?: boolean,
            namespaceName?: string // modification 2
        }
    }`

**Comment by Stonewon** [comment]
@strunkie30 is right! According to [index.js,](https://github.com/MetinSeylan/Vue-Socket.io/blob/caf4f56b106ffc3068f9aca3cb193137170e0241/index.d.ts) there is indeed documentation mistake. 'namespaceName' is also an option, thus the [index.d.ts](https://github.com/MetinSeylan/Vue-Socket.io/blob/8988085bef6bbf9ecdb5fced6b4220d5eb853bd3/src/index.js) should also be modified accordingly:

`type MultiSockets = {
    [key: string]: SocketIOClient.Socket
}'

‘declare module 'vue/types/vue' {
    interface Vue {
        $socket: SocketIOClient.Socket | MultiSockets, // modification 1
        sockets: {
            subscribe(eventName: string, handler: socketHandler<Vue>): void,
            unsubscribe(eventName: string): void,
        }
    }’

‘declare module 'vue-socket.io' {
    ...
    export interface VueSocketOptions {
        debug?: boolean;
        connection: string | SocketIOClient.Socket,
        vuex?: ...,
        options?: {
            useConnectionNamespace?: boolean,
            namespaceName?: string // modification 2
        }
    }`

**Comment by Stonewon** [comment]
@strunkie30 is right! According to [index.js,](https://github.com/MetinSeylan/Vue-Socket.io/blob/caf4f56b106ffc3068f9aca3cb193137170e0241/index.d.ts) there is indeed documentation mistake. 'namespaceName' is also an option, thus the [index.d.ts](https://github.com/MetinSeylan/Vue-Socket.io/blob/8988085bef6bbf9ecdb5fced6b4220d5eb853bd3/src/index.js) should also be modified accordingly:
```
type MultiSockets = {
    [key: string]: SocketIOClient.Socket
}

declare module 'vue/types/vue' {
    interface Vue {
        $socket: SocketIOClient.Socket | MultiSockets, // modification 1
        sockets: {
            subscribe(eventName: string, handler: socketHandler<Vue>): void,
            unsubscribe(eventName: string): void,
        }
    }

declare module 'vue-socket.io' {
    ...
    export interface VueSocketOptions {
        debug?: boolean;
        connection: string | SocketIOClient.Socket,
        vuex?: ...,
        options?: {
            useConnectionNamespace?: boolean,
            namespaceName?: string // modification 2
        }
    }
```
