### ISSUE TITLE
Vuex listener doesn't listen to the default "pong" event.

### ISSUE THREAD

**Issue by W4G1** [MetinSeylan/Vue-Socket.io#219]
**Describe the bug**
Socket.io has build in events such as "connection" and "pong" that get send by the server automatically. When I define a mutation listener for the "pong" event, It doesn't get fired when the server sends the event (other events do work though).

Not working example:
```javascript
const mutations = {
  SOCKET_pong (latency) {
    // Does not work
  }
}
```
This behavior only happens when declared as a mutation in Vuex. Surprisingly, when I listen to it on component level the event does actually get fired like it's supposed to.

Working example:
```html
<script>
export default {
  sockets: {
    pong (latency) {
      // Works!
    }
  }
}
</script>
```

**Expected behavior**
The "pong" listener defined as a mutation in Vuex, should be fired when the event gets send to the client.

**Comment by probil** [comment]
@W4G1 Consider using [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended)
