### ISSUE TITLE
update npm package, plz

### ISSUE THREAD

**Issue by zuochenxue** [MetinSeylan/Vue-Socket.io#220]
update npm package, plz

**Comment by mauritzn** [comment]
An update to the NPM package would make it a lot easier to use Vue-Socket.io with TypeScript, since the type definition added 6 months ago would be added to the package.

**Comment by tsengorz** [comment]
Right now I'm hardcoding the version to master as a workaround. A release would be great so I can follow semantic versioning.

**Comment by kattatzu** [comment]
Please update npm package.

```bash
Could not find a declaration file for module 'vue-socket.io'. 
'.../node_modules/vue-socket.io/dist/vue-socketio.js' has an "any" type implicitly.
Try `npm install @types/vue-socket.io`
if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-socket.io';`
```
