### ISSUE TITLE
this.sockets is undefined

### ISSUE THREAD

**Issue by sosukeinu** [MetinSeylan/Vue-Socket.io#222]
---
name: this.sockets is undefined
about: sockets object is not recognized in the Vue component

---

**Describe the bug**
`sockets` object is not recognized on Vue component when the component is originally loaded. However, it is recognized when webpack development server refreshes the page.

**Expected behavior**
Vue-Socket.io should subscribe to keys defined in sockets object when component is mounted.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 67.0

**Additional context**
I am not using vue-socket.io in the main.js, but am using it in a subcomponent. I am registering it like so:

```javascript
import Vue from 'vue'
import SocketIO from 'socket.io-client'
import VueSocketio from 'vue-socket.io'

export default {
  name: 'Socketio',
  mounted: function () {
    this.init()
  },
  sockets: {
    connect: function () {
      console.info('I expect to get this message when it connects')
    }
  },
  methods: {
    init () {
      let connection = 'http://mysocketserver:8080'
      Vue.use(new VueSocketio({
        connection: SocketIO(connection),
        debug: true
       }))
      this.sockets.subscribe('testEmit', (data) => {
        console.info('this is where I get an error. I also never receive a connection message. However, if I re-save the file, and the page hot reloads with webpack,...I get both of these working.')
       })
    }
  }
}
```

**Comment by oz-** [comment]
Replace 
`this.sockets`
by
`this.$socket`
(A $ and no 's' at the end.)

**Comment by ph1823** [comment]
Hi, I had the same problem, and it turns out that I had forgotten to declare the View-socket instance, so if you still have the problem, check your view-socket instance in your app.js
