### ISSUE TITLE
Cannot put mutations/actions/states into existing store (Using Nuxt in SPA mode)

### ISSUE THREAD

**Issue by AymLaf** [MetinSeylan/Vue-Socket.io#223]
**Describe the bug**
I tried to put actions/mutations/states of the websocket into existing store with others modules. I did that because I want to launch action set up in an other module.

**Expected behavior**
I'm going step by steps : 
- Connect to my server by doing "this.$connect();" (**working**)
- My server answer (in JSON) with action value ("sendHello") to start action when I get the answer (**working**)
- This action ("sendHello") send something to the server (**working**)
- An other answer happened from my server targetting an action ("answerCommit") (**working**)
- In this answer I get some stuff that I want to store in states by commiting them to update and reload my component. (**NOT working**, error : "Error: [vuex] do not mutate vuex store state outside mutation handlers.")

**Desktop :**
 - OS: Windows 10
 - Browser Chrome
 - Version 76.0

**Additional context**
I get all of this working by adding an other store (named store2) who contain all of websocket's stuff (actions,mutations,states) : 
![image](https://user-images.githubusercontent.com/37800130/64542665-43b92000-d324-11e9-8ba2-8cb0cef705ee.png)

My main store who is exported to Nuxt is : 
![image](https://user-images.githubusercontent.com/37800130/64542944-b1fde280-d324-11e9-8153-472bf3da6ff5.png)

In my components I'm able to access with mapGetters to my main store but that's all.

I alredy tried to configure my websocket with "passToStoreHandler" option but it didn't work better.
I already tried to put actions/mutations/states in the main store. Into a module and at the root definition.
I already tried to call mutation from my server.
I already tried to call an other action to commit when I receive the answer.

I followed this tutoriel : https://www.npmjs.com/package/vue-native-websocket

And here is my websocket configuration : 
![image](https://user-images.githubusercontent.com/37800130/64543212-1751d380-d325-11e9-8225-994ee498b661.png)

Please help me to commit this state and get it into my component to dynamically upload it.

Thank you :)

**Comment by germanllop** [comment]
I was able to use it just changing the mutation name from uppercase SOCKET_CONNECT to SOCKET_connect and it worked.
