### ISSUE TITLE
User Logout -> New User Login (different namespace)

### ISSUE THREAD

**Issue by Danail-Irinkov** [MetinSeylan/Vue-Socket.io#224]
I am struggling with updating the socket client to listen to the new socket namespace for the newly logged-in user from the same browser tab.

when installing the socket client again with vue.use(...)
vuex actions still keep listening to the previously connected socket....

**Comment by alex-m-l** [comment]
> I am struggling with updating the socket client to listen to the new socket namespace for the newly logged-in user from the same browser tab.
> 
> when installing the socket client again with vue.use(...)
> vuex actions still keep listening to the previously connected socket....

Thank you! Saved my day:)

**Comment by Danail-Irinkov** [comment]
Hi Alex :)

Not sure how I save you, but I struggled 2 days over this :D
