### ISSUE TITLE
The connect function is not executed

### ISSUE THREAD

**Issue by namesu** [MetinSeylan/Vue-Socket.io#229]
The server is connected, but the front end does not execute the connect function in the vue route.

**Comment by img2001jpg** [comment]
I have the same issue

**Comment by hcq11** [comment]
I have the same issue too

**Comment by cepm-nate** [comment]
Perhaps it would be nice if he shared the source behind the demos listed in the docs? My server clearly shows the connection as well, but no matter where I put the 'sockets:{} ' object (main.js, app.vue, component), I can't get the connect() function to fire either.
