### ISSUE TITLE
Prevent console.log messages

### ISSUE THREAD

**Issue by NdauwaRafael** [MetinSeylan/Vue-Socket.io#230]
**Prevent console.log messages**
I can't seem to prevent the package from logging message into the console.
Sometimes the messages logged display the emitted information.
 I would like to prevent this especially when building production.

**Comment by thislooksfun** [comment]
Don't pass `debug: true` to the `VueSocketIO` constructor.

**Comment by NdauwaRafael** [comment]
@thislooksfun Thank you so much  👏👏👏 . I had missed  that.
