### ISSUE TITLE
Is there any way to disable connection on startup?

### ISSUE THREAD

**Issue by robbelroot** [MetinSeylan/Vue-Socket.io#233]
Is there any way to let the plugin connect to the server later (not instantly)? Is this possible/not possible in general, or just not for this plugin?

**Comment by MarkCavalli** [comment]
```
options: {
  autoConnect: false
}
```

**Comment by vanwhebin** [comment]
Version：3.0.7 
it doesn't work
![image](https://user-images.githubusercontent.com/8357785/75653934-820f1680-5c99-11ea-909f-d5ed9cd39193.png)

**Comment by pavellzubkov** [comment]
@MarkCavalli 
> options: {
>   autoConnect: false
> }

```
Vue.use(new VueSocketIO({
  debug: true,
  autoConnect: false,
  connection: 'myserv_adr'
}))
```
it's not work
