### ISSUE TITLE
设置autoConnect=false之后怎样手动触发连接

### ISSUE THREAD

**Issue by BigYangBrother** [MetinSeylan/Vue-Socket.io#237]
我这边有个场景是这样，实例化的时候不需要建立连接，需要在某个事件中触发连接，我也试过将vueSocketio放在组件中的某个事件后进行实例化，但是服务端收到了我的连接我这边收不到connect事件的消息，后来在main.js中设置autoConnect=false，但是不知道怎样手动触发连接，特来请教一下，多谢🙏

**Comment by chaozgz** [comment]
`    mounted(){
        // this.$socket.open()
    }`

**Comment by JieenZhang** [comment]
// 重新连接websocket
util.reconnectWebSocket = function (vm, url) {
  let options = vm.$appconfig.websocketOpt
  options.autoConnect = true
  options.query.token = getStore(vm.$appconfig.tokenKey)
  vm.$vueSocketIo.connect(url, options)
}

但是有个BUG，需要重新添加 VueSocketIOListener, 不然重连的事件将失效

**Comment by xlm2017** [comment]
大佬 ,需要如何 重新添加 VueSocketIOListener ?
重新连接之后我还是无法监听到聊天的事件.
