### ISSUE TITLE
Is it possible to use sockets from Vuex commits

### ISSUE THREAD

**Issue by Gacnt** [MetinSeylan/Vue-Socket.io#24]
E.g. 
```
store.commit('enterQueue');

enterQueue: function(state) {
    state.socket.emit("enterQueue");
   // bunch of other code
}
```

Right now I'm working around it like this

```
const socket = io('http://localhost:3000');
const store = new Vuex //blah blah
Vue.use(VueSocketio, socket, store);
```

So I can use the socket global variable from within the store, as well as the socket functionality provided from this package

**Comment by mbouclas** [comment]
I second that. There should be a way to access the socket from within the store (like in actions). Right now, i too am doing some sort of a hack which is not pretty or right

Any ideas?

**Comment by mgostisha** [comment]
@Gacnt I think a better option would be to use a Vuex action that preforms the commit and returns a promise, then you can do your socket stuff from the component. Not that it's ultimately the best way to do it, but it might be a little cleaner than using globals everywhere!

**Comment by seanmthompson** [comment]
+1 to this. seems like this should be a basic feature

**Comment by ma53** [comment]
Originally posted this in #85 but I thought I'd post it here too in case anyone on the chain might find it useful.

Your mutations and actions can reference the root Vue instance via `this._vm`.  So, this is the method I've been using:

```
someAction(context, payload) {
    this._vm.$socket.emit('someEvent', someData);
}
```

Avoids instantiating a new Vue instance every time you need to emit an event.
