### ISSUE TITLE
NPM version 3.0.7 is missing last 5 commits to master.

### ISSUE THREAD

**Issue by larrylsharpe** [MetinSeylan/Vue-Socket.io#245]
**Describe the bug**
NPM version 3.0.7 is missing last 5 commits to master.
I particularly need: Handle more than one namespace (#207)

**Expected behavior**
expect to be able to create multiple namespace configs for use from the dist.
It worked as the documentation said from source but not from the npm dist.

Recommend publishing a new version to NPM

**Comment by MetinSeylan** [comment]
okay it's upgrading 🖖🏻
