### ISSUE TITLE
Unexpected token and the production build crashed

### ISSUE THREAD

**Issue by gorcsek** [MetinSeylan/Vue-Socket.io#248]
**Describe the bug**
Hy, today I found a bug your new release. 
The error in the console: 
ERROR in ./node_modules/vue-socket.io/dist/vue-socketio.js
Module parse failed: Unexpected token (10:14818).
The error only occurred when run production build. 
I fixed the 3.0.7 version to the package.json and everything works fine now. 

Thanks, 
Milan

**Comment by absir1949** [comment]
The same problem,please fix it .

**Comment by rafaelmartinsdacosta** [comment]
I have the same problem!

Any solution for the webpack version?

"vue-socket.io": "^3.0.7",
"webpack": "^3.11.0"

**Comment by tarikhagustia** [comment]
same here

**Comment by Akifcan** [comment]
i have same problem 
i installed 
npm install vue-socket.io@3.0.7
