### ISSUE TITLE
connect is not console.log

### ISSUE THREAD

**Issue by QianSu** [MetinSeylan/Vue-Socket.io#249]
**Describe the bug**
![image](https://user-images.githubusercontent.com/21114827/80911631-12390d00-8d6a-11ea-9af7-6dafa9274545.png)
![image](https://user-images.githubusercontent.com/21114827/80911644-22e98300-8d6a-11ea-8c11-61469688bcba.png)
![image](https://user-images.githubusercontent.com/21114827/80911650-2e3cae80-8d6a-11ea-8e51-ae56d3eb8c7f.png)

**Expected behavior**

  connect() {
      console.log("已链接");
    },

is not work.so why?
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikemissing** [comment]
Might be the same cause as for https://github.com/MetinSeylan/Vue-Socket.io/issues/250

**Comment by lieqiang** [comment]
@QianSu 遇到和你一样的问题，请问解决了吗？

**Comment by sison** [comment]
back to version **@3.0.5** and get resolve

**Comment by lhcdims** [comment]
I confirmed console.log is fired when set the version back to '=3.0.5' in package.json

```
"vue-socket.io": "^3.0.5",
```

**Comment by Zhoukaiqiang** [comment]
> I confirmed console.log is fired when set the version back to '=3.0.5' in package.json
> 
> ```
> "vue-socket.io": "^3.0.5",
> ```

Holly sh*t I got this problem two days, it works it works, thank you bro!!

**Comment by mohitsinghs** [comment]
I've published [vue-socket.io-fix](npm.im/vue-socket.io-fix) with same version numbers (v3.0.7, v3.0.9) with my patches from #261 so that people using this plugin suffer less.
Until this is fixed, append `-fix` in package name and reinstall.

I hope this helps others like me. Do let me know if something is still broken.
