### ISSUE TITLE
Vue-Socket.io: #connect subscribe, component: undefined 

### ISSUE THREAD

**Issue by gufyapk** [MetinSeylan/Vue-Socket.io#256]
sockets: {
    connect() {
      console.log('connect');
    },
}

**Comment by gufyapk** [comment]
use 3.0.9

**Comment by pslxx** [comment]
yeah,,me too!!!!!!!!!!!!!!!!!!!!!!!
after upgrade subscribe not work

**Comment by sujeetpillai** [comment]
Yes. This broke for us too. Component level socket subscriptions are broken. I get the plugin enabled message but no subscriptions.

**Comment by carlos00027** [comment]
help me please :)

**Comment by gebilaofan** [comment]
Is there any solution? I have been troubled for 3.0.7 and for a week   :(
