### ISSUE TITLE
Vue-Socket.io sockets function no perform

### ISSUE THREAD

**Issue by gufyapk** [MetinSeylan/Vue-Socket.io#257]
@vue/cli 4.2.3
Vue-Socket.io 3.0.9

I use vue-socket.io 3.0.9 sockets is not normal，use 3.0.7 is ok，why?

**Comment by pslxx** [comment]
yeah,me too!!!!!!!!!!!!!!!!11111

**Comment by hrr** [comment]
Same here, just downgraded to 3.0.5 and it worked again

**Comment by super21z** [comment]
Same for me , i also downgraded to 3.0.7

**Comment by pvkovalev** [comment]
"... socket.io subscribe is not a function ... "
Same here, downgraded to 3.0.7 from 3.0.9

**Comment by sonoscapeweb** [comment]
+1

**Comment by ninbert** [comment]
any of the options "this.sockets.subscribe"/"this.$sockets.subscribe","this.$socket.subscribe" not working. result => this.sockets.subscribe is not a function

**Comment by gaoquanbing-ausxin** [comment]
Vue-Socket.io 3.0.9
sockets is not work

this.sockets.subscribe  replaced by this.sockets.listener.subscribe

@ninbert

**Comment by ninbert** [comment]
@gaoquanbing-ausxin, Great!!!!!

what about 'sockets' property in the vue instance?

sockets: {
   a() {
    console.log("something")
}
}

the console.log wont fire when a() is activated from the server

**Comment by gaoquanbing-ausxin** [comment]
Because the bug in version 3.0.9,
sockets: {
a() {
console.log("something")
}
}

does not work, u can do as follow:
mounted() {
  this.sockets.listener.subscribe('a', (data) => {
    console.log("something")
  })
}

and the sockets is from vue-socket.io( import from main.js), and follow is my config

import VueSocketio from 'vue-socket.io'

Vue.use(new VueSocketio({
  debug: true,
  connection: socketio('ws://xx.xx.xx.xx:10342', {
    path: '',
    autoConnect: false,
    transports: ['websocket', 'xhr-polling', 'jsonp-polling']
  })
}))

@ninbert

**Comment by ninbert** [comment]
@gaoquanbing-ausxin 

and what to do in the state actions /mutations?

before it was 

mutations: {

     socketListenerA(){
            console.log("something")
     }

}

**Comment by princetc** [comment]
I don't know if I'm missing anything but seems connection between server and client can be created but on this version the listener function in the Vue life cycle methods does not seem to work

**Comment by gufyapk** [comment]
@princetc 

There are two options
1. Downgrade to version 3.0.7
2. Refer to the answers above

Can solve the problem, waiting for the official new version

**Comment by mohitsinghs** [comment]
v3.0.9 is indeed broken. I created #261 which should fix this.

**Comment by gebilaofan** [comment]
> Same for me , i also downgraded to 3.0.7

Can you use it normally after dropping to 3.0.7? My version has always been 3.0.7, it was still usable before, and problems have recently started.
```js
this.sockets.subscribe is not a function
```

And i found 
```js
new Vue({
  sockets:{
    connecting() {
      console.log('正在连接')
    },
    disconnect() {
        console.log("Socket 断开");
    },
    connect_failed() {
        cosnole.log('连接失败')
    },
    connect() {
      console.log('socket connected')
    },
    welcome: data => {
      cosnole.log('welcome', datat)
    }
  },
  router,
  store,
  render: h => h(App)
}).$mount('#app')
```
All events here are not executed
