### ISSUE TITLE
Breaking changes since v3.0.6

### ISSUE THREAD

**Issue by nodegin** [MetinSeylan/Vue-Socket.io#262]
3.0.6: Can start the project but got error in browser console

![Screenshot 2020-06-22 at 3 17 53 AM](https://user-images.githubusercontent.com/8536244/85233175-08ad5680-b437-11ea-9453-940e208e281c.png)

3.0.7: Cannot even build the project (Latest version 3.0.9 same)
<img width="861" alt="Screenshot 2020-06-22 at 3 14 57 AM" src="https://user-images.githubusercontent.com/8536244/85233216-37c3c800-b437-11ea-9edf-7a755f5dcfa0.png">

**Comment by mohitsinghs** [comment]
I've published [vue-socket.io-fix](npm.im/vue-socket.io-fix) with same version numbers (v3.0.7, v3.0.9) with my patches from #261 so that people using this plugin suffer less.
Until this is fixed, append `-fix` in package name and reinstall.

I hope this helps others like me.

**Comment by nodegin** [comment]
Not sure why closing this while no new verdion coming out, is this not going to fix?
