### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by xinbingyao** [MetinSeylan/Vue-Socket.io#263]
i use vue-socket.io in vue-cli project
```
Vue.use(new VueSocketIO({
  debug: true,
  connection:  'http://192.168.0.145:8015',
  options: {
    path:  '/wsapi/v1.0/join'
  }
}))
```
vue.config.js
```
devServer: {
  proxy: {
    '/wsapi': {
        target: 'http://192.168.37.130:5050',
        ws: true,
        changeOrigin: true
      },
      'sockjs-node': {
        target: 'http://192.168.37.130:5050',
        ws: false,
        changeOrigin: true
      }
  }
}
```
![image](https://user-images.githubusercontent.com/39030488/85514728-eb42dd00-b62e-11ea-86c8-8b0441183d2a.png)

**Comment by OrhanArslan** [comment]
Try like this:

Vue.use(new VueSocketIO({
  debug: true,
  connection:  'http://192.168.0.145:8015',
  options: {
    path:  '/wsapi/v1.0/join',
    transports: ['websocket'],
  }
}))

**Comment by OrhanArslan** [comment]
Try like this:

`Vue.use(new VueSocketIO({
  debug: true,
  connection:  'http://192.168.0.145:8015',
  options: {
    path:  '/wsapi/v1.0/join',
    transports: ['websocket'],
  }
}))`
