### ISSUE TITLE
Stop repeated polling requests

### ISSUE THREAD

**Issue by ben-lee222** [MetinSeylan/Vue-Socket.io#265]
Hi, I'm having a similar problem to #186  where if the express server that I'm listening to is down, the websocket client keeps making bad polling requests in the form of `...&transport=polling&t=...`

I've tried setting the transport options like this:
```
const port = '3002';
const ioAddress = `${window.location.hostname}:${port}`;

Vue.use(VueCookies);
Vue.use(new VueSocketIO({
  debug: process.env.NODE_ENV === 'development',
  connection: ioAddress,
  options: {
    transports: ['websocket'],
    reconnectionAttempts: 8,
  },
}));
```
and like this:
```
const port = '3002';
const ioAddress = `${window.location.hostname}:${port}`;

Vue.use(VueCookies);
Vue.use(new VueSocketIO({
  debug: process.env.NODE_ENV === 'development',
  connection: socketio(ioAddress, { transports: ['websocket'], reconnectionAttempts: 8 }),
}));
```
but both result in giving constant bad polling requests in addition to the websocket requests. How do I prevent the polling requests entirely?

**Comment by playvici** [comment]
what was solve?
