### ISSUE TITLE
this project seems to be abandoned for all practical purposes - use [vue-socket.io-extended](https://github.com/probil/vue-socket.io-extended) instead

### ISSUE THREAD

**Issue by guoxiangke** [MetinSeylan/Vue-Socket.io#267]
this project seems to be abandoned for all practical purposes - use [vue-socket.io-extended](https://github.com/probil/vue-socket.io-extended) instead

_Originally posted by @builder7777 in https://github.com/MetinSeylan/Vue-Socket.io/issues/217#issuecomment-610416739_

**Comment by tenutso** [comment]
I couldn't get this project to work as desired so I just rolled my own by putting the client-io connection to a Vue.prototype.socketio in main.js and the used it in my components as $socketio which is way more reliable. Hopefully, this project will get a second wind.

**Comment by MetinSeylan** [comment]
not abandoned, just underdevelopment for refactor
