### ISSUE TITLE
Namespaces are broken in 3.0.10

### ISSUE THREAD

**Issue by alex-m-l** [MetinSeylan/Vue-Socket.io#270]
Hello. I was using namespaces options (have several backends to connect to) and after another deploy figured out that I cant accces namespaces anymore. 

My config:
new VueSocketIO({
...
options: {
    useConnectionNamespace: true,
    namespaceName: 'customNamespace',
  }
})

Calling through:
this.$socket.customNamespace.emit(...)  - gives an error "emit is not a function".

Should such updates be in 3.1.0 version - because it is updated automatically through npm as minor version update and breakes your code?

v3.0.9 works fine with namespaces.

**Comment by MetinSeylan** [comment]
namespaces feature is reverted for now, it will re-release for next version

**Comment by Xoto1162** [comment]
> namespaces feature is reverted for now, it will re-release for next version

When the next version will be released ?
