### ISSUE TITLE
Version 3.0.9 doesn't connect

### ISSUE THREAD

**Issue by felipeminello** [MetinSeylan/Vue-Socket.io#275]
I try to connect to the vue component, but I can only do it in version 3.0.7, as described in Stackoverflow:

[https://stackoverflow.com/questions/61769716/vue-socket-connection-not-triggered](https://stackoverflow.com/questions/61769716/vue-socket-connection-not-triggered)

**Comment by MetinSeylan** [comment]
update to 3.0.10
