### ISSUE TITLE
Can I use with Vue 3?

### ISSUE THREAD

**Issue by vadimmarkov** [MetinSeylan/Vue-Socket.io#282]
Hello!

I have a problem. How can I use with Vue 3? Is support it?

**Comment by soulsam480** [comment]
I'm trying to set it up with Vue 3 on ts but is throws  an error
```javascript
vue-socketio.js?5132:10 Uncaught TypeError: Cannot set property '$socket' of undefined
    at t.value (vue-socketio.js?5132:10)
    at Object.use (runtime-core.esm-bundler.js?5c40:3360)
    at eval (main.ts?bc82:19)
    at Module../src/main.ts (app.js:1115)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1140)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
```

**Comment by lukaskoeller** [comment]
I set it up like this (see below). Instead of throwing errors, nothing is rendered to `#app`.

```javascript
import VueSocketIO from 'vue-socket.io';
import io from 'socket.io-client';
import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import router from './router';
import store from './store';

const socketio = new VueSocketIO({
  debug: true,
  connection: io('http://localhost:3000'),
  vuex: {
    store,
    actionPrefix: 'SOCKET_',
    mutationPrefix: 'SOCKET_',
  },
});

createApp(App)
  .use(store)
  .use(router)
  .use(socketio)
  .mount('#app');
```

**Comment by tbmpje** [comment]
In case others come across this same problem, I was able to fix it as follows:

1. Open file:
    "node_modules\vue-socket.io\dist\vue-socketio.js"

2. search for the following string (without the ""): 
    "t.prototype.$socket=this.io,t.prototype.$vueSocketIo=this"

3. replace it with the following (again without the ""): 
    "t.config.globalProperties.$socket=this.io,t.provide('socket',this.io),t.config.globalProperties.$vueSocketIo=this"

4. Then you can use it in Vue 3 (main.js) as follows: 
  ```
 import { createApp } from 'vue'
 import App from './App.vue'
 import router from './router'
 import SocketIO from 'socket.io-client'
 import VueSocketIO from 'vue-socket.io'

 const optionsVueIO = {
    debug: true,
    connection: SocketIO('http://localhost:3000')
 }

 const app = createApp(App).use(router).use(new VueSocketIO(optionsVueIO))            
 app.mount('#app')
```

To use the socket in the composition api (in a component) you have to inject it, simply declare it, e.g.: 
  ``` 
 const socket = inject('socket')
 console.log(socket)
```

**Comment by HaydenWoods** [comment]
> In case others come across this same problem, I was able to fix it as follows:
> 
> 1. Open file:
>    "node_modules\vue-socket.io\dist\vue-socketio.js"
> 2. search for the following string (without the ""):
>    "t.prototype.$socket=this.io,t.prototype.$vueSocketIo=this"
> 3. replace it with the following (again without the ""):
>    "t.config.globalProperties.$socket=this.io,t.provide('socket',this.io),t.config.globalProperties.$vueSocketIo=this"
> 4. Then you can use it in Vue 3 (main.js) as follows:
> 
> ```
> import { createApp } from 'vue'
> import App from './App.vue'
> import router from './router'
> import SocketIO from 'socket.io-client'
> import VueSocketIO from 'vue-socket.io'
> 
> const optionsVueIO = {
>   debug: true,
>   connection: SocketIO('http://localhost:3000')
> }
> 
> const app = createApp(App).use(router).use(new VueSocketIO(optionsVueIO))            
> app.mount('#app')
> ```
> 
> To use the socket in the composition api (in a component) declare it as follows:
> 
> ```
> const socket = inject('socket')
> console.log(socket)
> ```

This worked for me, thanks @tbmpje!

**Comment by djcaesar9114** [comment]
Watch out, although the solution given above works, it's not a canonical answer, and you may encounter some problems in the future.

**Comment by waverking** [comment]
I just tried to follow the way above and it really worked,but another problem come out like follows:
![捕获](https://user-images.githubusercontent.com/63185761/109421767-ab30c700-7a13-11eb-8885-6eae5e3c6ae9.JPG)
Whats going wrong with this?

**Comment by kadetXx** [comment]
> new VueSocketIO(optionsVueIO)

Thank you so so muchhh. I had the same problem, spent two nights searching for a solution and this worked perfectly!

**Comment by danielmarkavis** [comment]
So this commit:

https://github.com/MetinSeylan/Vue-Socket.io/commit/3337d432982c92486b398dcc48bc1762e340180a

Seems to add the above fix, but I'm still getting `Cannot set property '$socket' of undefined` error.

**Comment by aalex** [comment]
There is vue-3-socket.io : https://www.npmjs.com/package/vue-3-socket.io

**Comment by aalex** [comment]
It seems like this issue has not been fixed. Is this a "won't fix"?

**Comment by alexey-sh** [comment]
```
const socketPlugin = new VueSocketIO({
    debug: true,
    connection: io('http://localhost:3000', {
        withCredentials: false,
        autoConnect: true
    })
});
// fix bug https://github.com/MetinSeylan/Vue-Socket.io/issues/282
socketPlugin.install = (function (app: App) {
    // @ts-ignore
    app.config.globalProperties.$socket = this.io;
    // @ts-ignore
    app.provide('socket', this.io);
    // @ts-ignore
    app.config.globalProperties.$vueSocketIo = this
}).bind(socketPlugin);
```
