### ISSUE TITLE
Uncaught TypeError: Cannot set property '$socket' of undefined

### ISSUE THREAD

**Issue by soulsam480** [MetinSeylan/Vue-Socket.io#284]
`TypeError on Vue 3 with Typescript while installing the plugin with the new createApp.use() API.

main.ts
```javascript
const vSocket = new VueSocketIO({
    debug: true,
    connection: 'http://localhost:4000',
    /*  vuex: {
         store,
         actionPrefix: 'SOCKET_',
         mutationPrefix: 'SOCKET_'
     }, */
    /*  options: { path: "/my-app/" } //Optional options */
})
createApp(App).use(store).use(vSocket).mount('#app')
```
the error is 
```javascript
vue-socketio.js?5132:10 Uncaught TypeError: Cannot set property '$socket' of undefined
    at t.value (vue-socketio.js?5132:10)
    at Object.use (runtime-core.esm-bundler.js?5c40:3360)
    at eval (main.ts?bc82:19)
    at Module../src/main.ts (app.js:1115)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1140)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)
    at app.js:925
```
I think the problem is with the plugin installation while using Vue 3 with Typescript.

**Comment by soulsam480** [comment]
I think I figured out the problem. In Vue 3 when a plugin installs, the install function receives two parameters which are `app` from Vue 3's createApp method and `options` set by the user. [https://v3.vuejs.org/guide/plugins.html#writing-a-plugin](Vue 3 plugins).

So I think the problem is when the plugin installs and sets the instance method `$socket` using Vue 2's `Vue.prototype`  it breaks on Vue 3 as there is no such method. Instead, Vue 3 uses `app.config.globalProperties.$some_global_method` . 

I'm requesting the author to please have a look into this as Vue 3 has been released as stable.

**Comment by weishijun14** [comment]
Hi, already commit pr. :rofl: :rofl:
https://github.com/MetinSeylan/Vue-Socket.io/pull/287

**Comment by soulsam480** [comment]
Hey I just went through your pr. Have you tested it with Vue 2.x?

**Comment by weishijun14** [comment]
> Hey I just went through your pr. Have you tested it with Vue 2.x?

I have forked this repo, and fix install method,and publish to npm [this](https://www.npmjs.com/package/wsj.vue-socket.io),

I test my vue 3 project, not show `Uncaught TypeError: Cannot set property '$socket' of undefined` anyway :relaxed:

**Comment by soulsam480** [comment]
Sure, but have tested with vue 2.x

**Comment by weishijun14** [comment]
noop~

**Comment by weishijun14** [comment]
nope

**Comment by soulsam480** [comment]
> Hi, already commit pr. 🤣 🤣
> #287

here is a small tweak to your solution

```javascript
 /**
   * Vue.js entry point
   * @param Vue
   */

  install(Vue) {
    var version = Number(Vue.version.split(".")[0]);
    //if vue 3
    if (version === 3) {
      Vue.config.globalProperties.$socket = this.io;
      Vue.config.globalProperties.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    } else {
      Vue.prototype.$socket = this.io;
      Vue.prototype.$vueSocketIo = this;
      Vue.mixin(Mixin);
      Logger.info("Vue-Socket.io plugin enabled");
    }
  }
```

**Comment by grxc2312** [comment]
Has this problem been solved

**Comment by ZhengJie-99** [comment]
vue3 现在没啥周边资源好用

**Comment by livtech** [comment]
I downloaded vue socket from npm, but the /dist/vue-socketio.js still with ` t.prototype` , and the file from GitHub is with `t.config.globalProperties`. 
Have same way to update the npm?

**Comment by forealmy** [comment]
还是错误的
  "version": "3.0.10",
