### ISSUE TITLE
Namespaced SOCKET_ mutations

### ISSUE THREAD

**Issue by Danmer** [MetinSeylan/Vue-Socket.io#29]
SOCKET_ mutations are very useful but is there a way to make possible using them in namespaced store modules of Vuex? We can't catch even CONNECT inside the module, because it needs a module prefix. Or I don't understand something...

**Comment by MetinSeylan** [comment]
socket event is case sensitive on vuex, check it?

**Comment by Danmer** [comment]
Of course. But it doesn't help, cause it needs a prefix anyway.
`store.commit('SOCKET_CONNECT')` - works only in top level store or default modules
`store.commit('modulename/SOCKET_CONNECT')` - works in namespaced modules

**Comment by MetinSeylan** [comment]
yes, my bad its bug, added todo list "vuex modules"

**Comment by michgeek** [comment]
@MetinSeylan I don't think that's a bug, it has never been implemented to support deeply namespaced mutations
