### ISSUE TITLE
can i use Vue-socket.io in vuex state, actions or other

### ISSUE THREAD

**Issue by izcream** [MetinSeylan/Vue-Socket.io#3]
Can i use Vue-socket io in vuex file?
if it's can use how to?

Thanks

**Comment by MetinSeylan** [comment]
not yet :(

**Comment by MetinSeylan** [comment]
https://github.com/MetinSeylan/Vue-Socket.io/commit/8e0100be091c346115a019386cf18cdc527aa675

**Comment by MarlBurroW** [comment]
Is it possible to trigger vuex actions with sockets ? (like mutation with SOCKET_ prefix)

**Comment by almaweb** [comment]
Hello,
MarlBurroW  can you give a litte example please ?

**Comment by MarlBurroW** [comment]
Hello,
I've open an issue for this feature: https://github.com/MetinSeylan/Vue-Socket.io/issues/34
