### ISSUE TITLE
plugin.apply is not a function

### ISSUE THREAD

**Issue by Garik-** [MetinSeylan/Vue-Socket.io#30]
Hello. I do not know much english, so I use a translator. I have extensive experience in backend, but little experience frontend.

I have a simple project and easy task, I do not need to use webpack or other. 
That's where I started: 
#### index.html
```
<div id="app">
	<input v-model="name"><br>
	<textarea v-model="message"></textarea><br>
	<button @click.prevent="send">Send</button>
</div>
<script src="js/vendor/vue.js"></script>
<script src="js/vendor/build.js"></script>
<script src="js/main.js"></script>
```
#### main.js
```
console.log(VueSocketio);
Vue.use(VueSocketio, 'http://host:8080');
```
#### console
```
Object {default: Object, __esModule: true}
vue.js:3450 Uncaught TypeError: plugin.apply is not a function
```
Of course I was looking for [ways to solve this problem](https://forum.vuejs.org/t/plugin-apply-is-not-a-function-creating-plugin-in-vue-js/953/2?u=ridermansb), try install webpack and rebuilt the project - did not help.

**Comment by MetinSeylan** [comment]
this can help you
`
Vue.use(VueSocketio.default, 'http://host:8080');
`
