### ISSUE TITLE
How change EIO to 4?

### ISSUE THREAD

**Issue by mr-Abdrahimov** [MetinSeylan/Vue-Socket.io#317]

**Comment by BigTimerr** [comment]
Are you change EIO to 4？Please tell me！

**Comment by mr-Abdrahimov** [comment]
> Are you change EIO to 4？Please tell me！

Sorry, I don’t remember in which project I solved this problem and I don’t remember how I solved it either

**Comment by BigTimerr** [comment]
That‘s ok。Thanks you！
