### ISSUE TITLE
Vuex + IE

### ISSUE THREAD

**Issue by sanyashvets** [MetinSeylan/Vue-Socket.io#33]
Hi to all
Get error in IE11: SCRIPT5009: "Proxy" is not defined. File: eval code (4200), string: 1, column: 30095. Sample of code there : 
```
t.prototype.$socket=r.Socket,t.mixin({beforeCreate:function(){var t=this,e=this.$options.sockets;this.$options.sockets=new Proxy({},{set:function(e,n,r){return a.default.addListener(n,r,t),e[n]=r,!0},deleteProperty:function(e,n){return a.default.removeListener(n,t.$options.sockets[n],t),delete e.key,!0}})
```
Error is on ``` this.$options.sockets=new Proxy ``` moment. How to solve this ?

Also I`m using babel-polyfill to make promises work on IE

**Comment by zverbeta** [comment]
This issue is on ios 8.3 too

Becouse es5 doesn't support new Proxy. I found this module https://github.com/GoogleChrome/proxy-polyfill

**Comment by exprodrigues** [comment]
@zverbeta, I tried to use this module, but received the following error:

`Proxy polyfill does not support trap 'deleteProperty'`

**Comment by zverbeta** [comment]
I have got also this error, but forgot leave feedback. No one polyfill doesn't work with proxy `deleteProperty`. If you won't use vuex you can make mixin, something like that


`
Vue.prototype.$socket = Socket;

Vue.mixin({
  methods: {
  created(){
    let sockets = this.$options['sockets'];

    if(sockets){
      Object.keys(sockets).forEach((key) => {
        if(typeof sockets[key] == 'function') {
          this.$socket.on(key, sockets[key].bind(this));
        }
      });
    }
  },
  beforeDestroy(){
    const sockets = this.$options['sockets'];

    if(sockets){
      Object.keys(sockets).forEach((key) => {
        delete this.$options.sockets[key]
      });
    }
  }
});`

**Comment by Chaaang** [comment]
Did you solve this problem ? @zverbeta

**Comment by ghostTing** [comment]
Did someone solve this problem ? Please tell me what to do ， thanks a lot

**Comment by probil** [comment]
Try [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended) instead. It works fine in browsers with no `Proxy API` support (IE11, Chrome 37, etc)
