### ISSUE TITLE
Openshift hosting

### ISSUE THREAD

**Issue by rushstrike** [MetinSeylan/Vue-Socket.io#37]
Hello is it possible to specify a different Port when doing the handshake to upgrade from HTTP to WS (or HTTPS to WSS)?

The problem is that OpenShift PaaS uses ports 80/443 for HTTP and HTTPS. However, it listens for WS/WSS traffic on 8000/8443  .

For example this code will not work for OpenShift:

if (process.env.NODE_ENV === 'production') {
   Vue.use(VueSocketio, 'https://xxxxxx.rhcloud.com/socket.io/');
}

Since the code detects https it will assume that when upgrading to WSS it will use port 443 and it wont be able to complete the handshake. What I need is to specify HTTPs traffic = 443 but WSS to use 8443. 

I would appreciate if someone could point me where to change socket.io client code or the vue-socket.io. THank you.

**Comment by MetinSeylan** [comment]
this package is only client side :(

**Comment by rushstrike** [comment]
Yes my question is to configure client side port when initiating connection to the host
