### ISSUE TITLE
Is there a way to instantiate connection inside a component?

### ISSUE THREAD

**Issue by jokeronaldo** [MetinSeylan/Vue-Socket.io#4]
Is possible to connect inside a component? I mean, not in main.js but in a module, something like Login.vue

**Comment by jefflam** [comment]
Got the same question as well!

**Comment by pinguinjkeke** [comment]
Stuck with same

**Comment by jokeronaldo** [comment]
LOL, duplicated but where is the first issue link?

**Comment by ribaa** [comment]
It is possible to init connection in component?

**Comment by edoecohen** [comment]
@MetinSeylan any thoughts on this? Would be great if you could instantiate the socket connection not in main.js and not when app is created, but later, say after user has logged in.

**Comment by jacobgoh101** [comment]
it can be done by through socket.io options

https://socket.io/docs/client-api/#socket-open

something like this
```
Vue.use(new VueSocketIO({
    connection: SocketIO('http://metinseylan.com:1992', {   autoConnect: false }),
  })
);
```
