### ISSUE TITLE
Problem listning socket events on vuex actions

### ISSUE THREAD

**Issue by ivoribeiro** [MetinSeylan/Vue-Socket.io#42]
Hi, thank you for your work in this package.
I'm not been able to listning socket events on vuex actions , tell me if i'm doing it wrong .

vuex action function :
```
socket_myEvent: (context) => {
   //some code
  }
```
socket.io emit 

``` 
socket.emit('myEvent');

thanks

**Comment by MarlBurroW** [comment]
Hello, i'm using the version 2.1.1-a and your code working.


```javascript
// My backend
socket.emit('myEvent');
console.log('Event emmited')
```
`
```javascript
// In my vuex store
const actions = {
  socket_myEvent () {
    alert('Event recieved !')
  }
}
```
Popup is displayed as expected

**Comment by ivoribeiro** [comment]
The problem i was in 2.1.0 :( :-1:  , should reference the action suport on README
Thanks
