### ISSUE TITLE
Difference between Vuex Actions and Mutations

### ISSUE THREAD

**Issue by FPierre** [MetinSeylan/Vue-Socket.io#44]
I don't understand between Vuex Actions and Mutations with sockets:

I fully understood this #42 (Actions are called when socket server send an event).
But how to uses Mutations with sockets?

Thanks!

**Comment by ivoribeiro** [comment]
The same way but with the prefix SOCKET_

**Comment by FPierre** [comment]
A basic lifecycle with Action:

```js
// 1. in App.vue (client side)
// Emit Socket event to server
this.$socket.emit('move', currentPosition)

// 2. server.js (server side)
// Get Socket event from client and send a new one
socket.on('move', (currentPosition) => {
  // ...
  socket.emit('moved', newPosition)
})

// 3. in actions.js (Vuex, client side)
// Get Socket event from server
socket_moved: (context, newPosition) => {
  // Commit standard Mutation
  context.commit('position', newPosition)
}
```

I'm right?

But I still don't understand how to use Socket Mutations. A lifecycle example could be interesting.

**Comment by gil0mendes** [comment]
The idea is the same as native Vuex. You can use async code on actions, but you must not use it on mutations.

**Comment by fyyyyy** [comment]
https://www.youtube.com/watch?v=kRI4YLMjgHQ&index=4&list=PL55RiY5tL51pT0DNJraU93FhMzhXxtDAo
good explanation
<iframe width="560" height="315" src="https://www.youtube.com/embed/kRI4YLMjgHQ?list=PL55RiY5tL51pT0DNJraU93FhMzhXxtDAo" frameborder="0" allowfullscreen></iframe>
