### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by cb109** [MetinSeylan/Vue-Socket.io#45]
It would be great if `vm.$socket.emit()` would allow for broadcasting to all other clients in one way or another, e.g. following the socket.io API like `vm.$socket.broadcast.emit()` .

My current workaround is to first emit from Vue, then broadcast using the original client on the server.

**Comment by Oleg-Arkhipov** [comment]
Vue-Socket.io has nothing to do with that, as that is not possible. Only socket.io server is able to broadcast events to clients, so your solution is not a workaround, it is the primary solution.
