### ISSUE TITLE
this.store.commit is not a function (using Vuex)

### ISSUE THREAD

**Issue by JulienBonnin-ABTasty** [MetinSeylan/Vue-Socket.io#49]
Hello :)

I have an issue when I try to move my socket.io receivers from a component to my vuex store.
I simply added a SOCKET_CONNECT event into my store mutations, and it throws an error everytime its called.

`import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex);

const state = {
	notes: [],
	activeNote: {}
};

const mutations = {

	ADD_NOTE (state) {
		const newNote = {
			text: 'New note',
			favorite: false
		};
		state.notes.push(newNote);
		state.activeNote = newNote
	},

	EDIT_NOTE (state, text) {
		state.activeNote.text = text
	},

	DELETE_NOTE (state) {
		state.notes.$remove(state.activeNote);
		state.activeNote = state.notes[0]
	},

	TOGGLE_FAVORITE (state) {
		state.activeNote.favorite = !state.activeNote.favorite
	},

	SET_ACTIVE_NOTE (state, note) {
		state.activeNote = note
	},

	SOCKET_CONNECT () {
		console.log('USER IS CONNECTED TO THE SOCKET')
	}
};

export default new Vuex.Store({
	state,
	mutations
});
`

It's not only for the SOCKET_CONNECT event, I tried a custom event 'SOCKET_PING' and I have the same error. I had no problem when those events are located in a component.

The error is "this.store.commit is not a function".

Any ideas ?

Here is how I linked my store the Vue-Socket.io

`
import Vue from 'vue'
import store from './vuex/store'
import App from './components/App.vue'
import VueSocketio from 'vue-socket.io'

Vue.use(VueSocketio, 'http://localhost:3000/', store);

new Vue({
  store,
  el: 'body',
  components: { App }
});
`

Thanks in advance :)

**Comment by mtancoigne** [comment]
hm... should'nt you use `this.$store` instead of `this.store` ?
