### ISSUE TITLE
Demo site broken

### ISSUE THREAD

**Issue by nueverest** [MetinSeylan/Vue-Socket.io#5]
On this page: http://metinseylan.com/vuesocketio/ When I click "Join chat" button nothing happens.

I went to the console and saw this: `Failed to load resource: the server responded with a status of 404 (Not Found)`.

Thanks for building this.

**Comment by MetinSeylan** [comment]
fixed chat app and added new demo [http://metinseylan.com](http://metinseylan.com)

Thanks for feedback
