### ISSUE TITLE
ie problem

### ISSUE THREAD

**Issue by almaweb** [MetinSeylan/Vue-Socket.io#50]
Hello,
I have this problem width ie ;
L’objet ne gère pas la propriété ou la méthode « startsWith »

**Comment by pinguinjkeke** [comment]
The giant lodash for small check?
It can be done with ```string.indexOf('SOCKET_') === 0```

**Comment by jeystaats** [comment]
Never thought of it in that way. +1 @pinguinjkeke

**Comment by probil** [comment]
Try [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended) instead. It works fine in browsers with no `Proxy API` support (IE11, Chrome 37, etc)
