### ISSUE TITLE
Can’t pass multiple arguments

### ISSUE THREAD

**Issue by huhk-sysu** [MetinSeylan/Vue-Socket.io#51]
I wrote like this on the server side:
```javascript
io.emit('test', 'param1', 'param2', 'param3')
```

I can get all the three arguments when using `socket.io-client`
```javascript
socket.on('test', function () {
  console.log(arguments)
})

// result:
["param1", "param2", "param3"]
```
![result](http://oo8f7xkzp.bkt.clouddn.com/issue1.png)

But I can only get the first argument with `vue-socket`
```javascript
sockets: {
    test: function () {
      console.log(arguments)
    }
}

// result:
["param1"]
```
![result](http://oo8f7xkzp.bkt.clouddn.com/issue2.png)

**Comment by huhk-sysu** [comment]
I think the problem come from here:

In `Obeserver.js`, line 21~25
```javascript
this.Socket.onevent = (packet) => {
    Emitter.emit(packet.data[0], packet.data[1]);  // !!!!

    if(this.store) this.passToStore('SOCKET_'+packet.data[0], packet.data[1])
};
```

While packet.data contains the event's name and the arguments: 
![image](https://cloud.githubusercontent.com/assets/14769033/25173746/df217bf8-2527-11e7-92d4-5d734fa1da12.png)

Maybe it should be written like this:
```javascript
this.Socket.onevent = (packet) => {
    Emitter.emit(packet.data[0], packet.data.slice(1));  // !!!!

    if(this.store) this.passToStore('SOCKET_'+packet.data[0], packet.data[1])
};
```

**Comment by jeystaats** [comment]
+1 for @huhk-sysu , I'm using Laravel Echo in combination with Vue-Socket. And Echo returns three arguments, Event, Channel and data. Now Vue-Socket is kinda useless with this combination because it always returns the channel-name. Example below :
<img width="434" alt="screen shot 2017-05-02 at 10 43 24" src="https://cloud.githubusercontent.com/assets/2018788/25610626/433fbff4-2f24-11e7-9c38-884077a1882c.png">
Love to see a new update! 👍

**Comment by michgeek** [comment]
vuex mutations and actions do not support multi arguments as per the documentation https://vuex.vuejs.org/en/mutations.html You will need to use object payload if you need multiple arguments

The signature of mutations and actions are described there https://vuex.vuejs.org/en/api.html

```js
mutations: {
  increment (state, payload, options) {
    state.count += payload.amount
  }
},
actions: {
  checkout (context, payload, options) {
     // ....
    )
  }
}
```

All changes for multiple arguments should have never been merged. Build `2.1.1-b` is not compatible with store vuex
