### ISSUE TITLE
ie , android phone error

### ISSUE THREAD

**Issue by BusyHe** [MetinSeylan/Vue-Socket.io#56]
![image](https://cloud.githubusercontent.com/assets/17348825/25801534/936308fa-3420-11e7-802e-9f6b06ea0218.png)

**Comment by jeystaats** [comment]
Pleaase give some more detailed information on how and what . Plus it makes it more difficult to read it in non-English.

We can't do anything with just a console log.

**Comment by ghostTing** [comment]
i met the same problem， IE doesn support Proxy Class ，but i do not know how to deal with

**Comment by probil** [comment]
Try [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended) instead. It works fine in browsers with no `Proxy API` support
