### ISSUE TITLE
is not assignable to parameter of type 'ComponentOptions<Vue>

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [MetinSeylan/Vue-Socket.io#57]
Hello,
I just installed the package and set it up in my main.ts (yes typescript) as:

import * as VueSocketio from 'vue-socket.io';
import * as  socketio from 'socket.io-client';
Vue.use(VueSocketio, 'http://socketserver.com:1923');

var vm = new Vue({
 sockets:{
    connect: function(){
      console.log('socket connected')
    },
    customEmit: function(val){
      console.log('this method was fired by the socket server. eg: io.emit("customEmit", data)')
    }
  }
});

But my compiler and complains that:

./src/main.ts
(43,1): error TS2345: Argument of type '{ sockets: {}; router: VueRouter; store: Store<{ AppName: string; UserID: number; Crumb: string; ...' is not assignable to parameter of type 'ComponentOptions<Vue>'.
  Object literal may only specify known properties, and 'sockets' does not exist in type 'ComponentOptions<Vue>'.

**Comment by SmarterPhoneLabs** [comment]
Bump?

**Comment by jeystaats** [comment]
I think it misses the third argument, a Vuex store :) 

`Vue.use(VueSocketio, 'http://socketserver.com:1923' ,new Vuex.Store({
 // store logic for Vuex.Store
});`

**Comment by SmarterPhoneLabs** [comment]
When I try to supply a store as an argument, my compiler complains:

ERROR in ./src/main.ts
(26,1): error TS2346: Supplied parameters do not match any signature of call target.

**Comment by SmarterPhoneLabs** [comment]
Bump?

**Comment by SmarterPhoneLabs** [comment]
Would be really great if someone could chime in on this.
Thanks,

**Comment by clintonyeb** [comment]
@SmarterPhoneLabs That is because you failed to do as you were told.

The documentation is clear:

```
import VueSocketio from 'vue-socket.io';
Vue.use(VueSocketio, 'http://socketserver.com:1923');
```

See, there are no '* as blabla' in my imports. 
Also you don't need to import the socket.io-client. It uses the same connection internally if you don't. 

With regards.
