### ISSUE TITLE
Proxy is not defined - IE 11

### ISSUE THREAD

**Issue by drozdzynski** [MetinSeylan/Vue-Socket.io#58]
Hello,

in version 2.1.* you add Proxy object, and after that my app not work in IE 11, becouse in IE 11 is no Proxy object.

**Comment by wannymiarelli** [comment]
+1
This is a big problem, actually also " old version " of chrome ( v37 for example ) have the same problem.

**Comment by mashpie** [comment]
+1 - any updates on this?

**Comment by gbogard** [comment]
+1

**Comment by Yifei022** [comment]
+1

**Comment by francoisrousseau** [comment]
+1

**Comment by sromer** [comment]
+1

I tried implementing the ProxyPolyfill (https://github.com/GoogleChrome/proxy-polyfill) but it does not support the 'deleteProperty' trap, so it is no good to us.

Anyone got any ideas?

**Comment by bugs181** [comment]
I was wondering where that Proxy error came from. Looks like it happened around the time that I added Socket.io to the project.

**Comment by richcorbs** [comment]
+1

Just came across this now too.

**Comment by Chaaang** [comment]
Proxy cannot be pollify， SO I think this should be replaced by other method.

**Comment by partyka1** [comment]
+1 same here

**Comment by Chaaang** [comment]
About half a year passed..........

**Comment by bguivarch** [comment]
+1

**Comment by andreasvirkus** [comment]
Any resolution for this? 😕  😞

**Comment by yefeng2016** [comment]
+1
old version " of chrome ( v43 for example ) have the same problem

**Comment by Chaaang** [comment]
@partyka1 Hope you can fix this.pls

**Comment by probil** [comment]
Try [`vue-socket.io-extended`](https://github.com/probil/vue-socket.io-extended) instead

**Comment by QuentinouLeTwist** [comment]
@probil man you are my Hero !
