### ISSUE TITLE
How to correctly create a custom socket method?

### ISSUE THREAD

**Issue by nueverest** [MetinSeylan/Vue-Socket.io#6]
The details of this question are documented in this stackoverflow post.  It seemed like too much to put here.

http://stackoverflow.com/questions/39282843/how-to-correctly-create-a-custom-socket-method-with-vue-socket-io

As a side note, it would be cool if you had more examples including a dirt-simple example in which only localhost is used along with a button and a custom socket.

**Comment by MetinSeylan** [comment]
Hi,
`sockets` object only listen server side coming events,
and "this.$socket" is native `socket.io-client` object, `this.$socket.emit()` method is emit event from client to server.

good luck.

**Comment by nueverest** [comment]
Are you saying that I should using push()?

**Comment by MetinSeylan** [comment]
### Correct usage

server.js (server side)
```javascript
var socket = require('socket.io');
var io = socket.listen(1923);

io.on('connection', function(client){

    client.on('client_event1', function(name){
        client.emit('server_emit1', 123);
    });

    client.on('client_event2', function(name){
        client.emit('server_emit2', 123);
    });

});
```

script.js (client side)
```javascript
var metin = 'http://metinseylan.com:1923';

Vue.use(VueSocketio, metin); 

var vm = new Vue({
    el: '#vue-socket-dynamo',
    sockets:{
        server_emit1: function(val){     // client.emit('server_emit1', 123);
            console.log(val);
        },
        server_emit2: function(val){
            console.log(val);
        }
    },
    methods: {
        clickButton: function(val){
            this.$socket.emit('client_event1', val);      
            this.$socket.emit('client_event2', val);   
        }
    }
});
```
