### ISSUE TITLE
Force websocket

### ISSUE THREAD

**Issue by quenti77** [MetinSeylan/Vue-Socket.io#62]
How force to use websocket ?

On the server node with **socket.io** :
```javascript
import * as socket from 'socket.io'
const port = 1337
const io = socket(port, {
  transports: ['websocket']
})
```
In my app electron-vue i have this error :
```
http://localhost:4100/socket.io/?EIO=3&transport=polling&t=Lmnk47U 400 (Bad Request)
```

*Sry for my english*

**Comment by felixheck** [comment]
same here

**Comment by codeofsumit** [comment]
yup, need that as well

**Comment by codeofsumit** [comment]
as a temporary workaround you can require the library that is used internally and create your own socket instance that you pass to Vue-Socket.io

```
import io from 'socket.io-client';
import VueSocketio from 'vue-socket.io';

const socketInstance = io('http://localhost:3333', {
  transports: ['websocket'],
});

Vue.use(VueSocketio, socketInstance, store);

```

**Comment by felixheck** [comment]
Hi @MetinSeylan, would you mind sharing the reasons for closing this issue?
Is there a new related release?

**Comment by itoonx** [comment]
Not working with the lastest version

**Comment by MetinSeylan** [comment]
try like this
`
Vue.use(new VueSocketIO({
    debug: true,
    connection: socketInstance,
    vuex: {
        store,
        actionPrefix: 'SOCKET_',
        mutationPrefix: 'SOCKET_'
    }
}))
`

**Comment by xlkit456852** [comment]
@MetinSeylan  Thank you , it works
