### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by RokasMuningis** [MetinSeylan/Vue-Socket.io#69]
Most popular vue plugins supports typescript just fine, however this one doesn't.

Are there any plans for that?

**Comment by alesma** [comment]
Hi, you need to augment existing Vue Component type, check https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

I solved by adding this code:

```
declare module 'vue/types/vue' {
  interface Vue {
    sockets: any;
  }
}

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    sockets?: any;
  }
}
```

**Comment by Renari** [comment]
@olegshtch problem with using types here is that sockets is an object full of emitters and to my knowledge there's no way to specify an object with varying numbers of elements unless using an array.

**Comment by jubairsaidi** [comment]
`this.$socket` should be an instance of `io.Socket` no?

**Comment by andreixk** [comment]
this package does not work out of the box with a typescript project, why was this ticket closed?

**Comment by builder7777** [comment]
this project seems to be abandoned for all practical purposes - use [vue-socket.io-extended](https://github.com/probil/vue-socket.io-extended) instead
