### ISSUE TITLE
build vue-socket.io ERROR

### ISSUE THREAD

**Issue by GuangTianLi** [MetinSeylan/Vue-Socket.io#70]
Hash: 2ff386685ec4b1ecb1b4
Version: webpack 2.2.1
Time: 915ms
       Asset    Size  Chunks             Chunk Names
    build.js  223 kB       0  [emitted]  main
build.js.map  278 kB       0  [emitted]  main

ERROR in build.js from UglifyJs
SyntaxError: Unexpected token: punc ({) [./src/Emitter.js:1,0]

**Comment by wfsm** [comment]
@GuangTianLi I have this issue with the newest 3.0.0 version, how did you fix it?
