### ISSUE TITLE
Error try post message $socket.emit

### ISSUE THREAD

**Issue by thavoo** [MetinSeylan/Vue-Socket.io#72]
![image](https://user-images.githubusercontent.com/6331999/28131110-eaa6e64a-6706-11e7-9980-6a659ec57ab8.png)

error try post message error:
TypeError: Cannot read property '$socket' of undefined
    at profile.js:31707
    at <anonymous>

**Comment by thavoo** [comment]
i solved import var $socket

**Comment by miranium** [comment]
What did you do to import var $socket? I am getting the same error.

**Comment by Imbuzi** [comment]
Same error too ... how can I import $socket ?
