### ISSUE TITLE
vue-socket.io eventName issues

### ISSUE THREAD

**Issue by SunshineIce** [MetinSeylan/Vue-Socket.io#74]
I followed your project on vue-socket.io, you must be experienced with vue-socket.io module.  Could you pls help to fix below issue, thank you?

 For example, the server emit the event 'account.login', then i should code as below to listen on the event, right? But it didn't work. Should i put the quotation marks between the name please?

 sockets: {
      connect: function(){
          console.log('socket connected');
      },
      'account.login': function(val){

      },
  },

**Comment by RizkiHabibie** [comment]
Try:

sockets: {
connect: function(){
console.log('socket connected');
},
account.login: function(val){

  },
},

**Comment by nuttakit** [comment]
I just use this
this.$options.sockets['account.login'] = (message) => {
  // thing to do when get event
}

**Comment by Tamn9208** [comment]
@nuttakit where should this 
this.$options.sockets['account.login'] = (message) => {
// thing to do when get event
}
add?
i use it like this
export default {
this.$options.sockets['account.login'] = (message) => {
// thing to do when get event
}
}
but it's error
