### ISSUE TITLE
Package not maintained anymore

### ISSUE THREAD

**Issue by ncoden** [MetinSeylan/Vue-Socket.io#76]
This package is not maintained anymore. Lot of issues and pull requests are not reviewed.
@MetinSeylan Please transfer the repository ownership or add moderators.

**Comment by Oleg-Arkhipov** [comment]
@MetinSeylan any response?

**Comment by jeystaats** [comment]
Can't anyone make a fork and go on with that one? Love to contribute .

**Comment by ncoden** [comment]
Because of:
- No response to this issue in two weeks
- Last activity from @MetinSeylan 4 months ago
- No reply to issues or PRs since

And because we need fixes and new features, we do not want to all have our personal fork with custom fixes each in our own corner ;

**I created a "community" fork: https://github.com/vue-socket-io/Vue-Socket.io**

I will add to the organization the contributors of this repo.  If @MetinSeylan manifest himself and become active, the organization property will be transferred to him.

**Comment by MetinSeylan** [comment]
guys don't worry, i will release v3.0 soon

**Comment by ncoden** [comment]
I still think that a community-leaded package would be a good idea, or at list with several maintainers.
