### ISSUE TITLE
Use Sockets on Components.

### ISSUE THREAD

**Issue by yourivandenbrand** [MetinSeylan/Vue-Socket.io#78]
Do the sockets only work on the main App.vue? Been trying to get this to work on single file child components without avail. It just doesn't emit. If I however add the "socket.on" on the upper parent it does work. Would like to seperate my socket calls to their respective components instead of having to launch all the socket function from the parent(App.vue) to keep things organized. Is there something I'm doing wrong or isn't this possible?

**Comment by Nordes** [comment]
On my side it worked without any issue.
Example: 
main.js 
```
// ...
import VueSocketio from 'vue-socket.io'
Vue.use(VueSocketio, 'http://localhost:3000/notif')
// ...
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```
app.vue
```
export default {
  name: 'app',
  components: {
// ...
  }
}
```

testComponent.vue
```
import toastr from 'toastr'
// ...

export default {
  name: 'Test',
  // https://github.com/MetinSeylan/Vue-Socket.io
  sockets: {
    disconnect: function () {
      console.log('socket to notification channel disconnected')
    },
    connect: function () {
      console.log('socket to notification channel connected')
    },
    punch: function (val) {
      console.log('this method was fired by the socket server. eg: io.emit("punch", data)')
      toastr.info(`${val}`)
    }
  },

  data () {
    return {
      something: [
         // ... something here for the data if you need.
      ]
    }
  },

  created () {
    // Should attatch to socket.io service and then pull the data.
    toastr.info('Hello toast?')
  }
}
```

**Comment by bugs181** [comment]
My component is activated much later in the App life cycle. I'm having the same problem as the op. My layout looks identical to @Nordes, but it's not working for me.

**Comment by Iworb** [comment]
Can someone provide working example on [Quasar Play](http://quasar-framework.org/quasar-play/android/index.html#/showcase) app?
