### ISSUE TITLE
sockets property initialize failed

### ISSUE THREAD

**Issue by haruair** [MetinSeylan/Vue-Socket.io#8]
Binding the socket events is not working correctly on vue^2.0.0.

https://github.com/vuejs/vue/commit/71a0f3e1ef2a1c5452c211712f070bf37e93830e#diff-a3983d8041c692bde114459c55b587ebL18

I think `this.$options.hasOwnProperty("sockets")` should change to `this.$options["sockets"]` for the prototyped property just like [other codes in vuejs](https://github.com/vuejs/vue/blob/ae93d2bef8e20402ae3501aa5cdcf14b0ee19c12/src/core/instance/lifecycle.js#L194).

**Comment by MetinSeylan** [comment]
will be updated soon for vue 2

**Comment by MetinSeylan** [comment]
new release https://github.com/MetinSeylan/Vue-Socket.io/commit/7f5fac27d0623ccadd36af3f6b5fcf72eb5c6445
