### ISSUE TITLE
Connect to a random socket.io port

### ISSUE THREAD

**Issue by kofimokome** [MetinSeylan/Vue-Socket.io#80]
I recently deployed my vuejs + vue-socket.io app to Heroku.<br>From the vue-socket.io documentations, the url and port are specified during initialisation. But heroku give me a random port use for socket io. Is there a way I can initialise vue-socket-io to use a random port given to me by Heroku?<br>If I import the socket.io.js file, all I need to do is this `var socker = io()` and I will be connected to any  socket.io server.<br>Please how can I do this with vue-socket-io?

**Comment by kofimokome** [comment]
Seen a solution

**Comment by F5F5** [comment]
@kofimokome How did you solve this problem? My problem is similar to you.
