### ISSUE TITLE
In nuxt, this.$socket is undefined

### ISSUE THREAD

**Issue by cscan** [MetinSeylan/Vue-Socket.io#83]
I create a plugin, 

import Vue from 'vue'
import VueSocketio from 'vue-socket.io'
Vue.use(VueSocketio, 'http://localhost:3000')

and necessary setup in nuxt.config.js

then I write a page, example test.vue:

export default {
  sockets: {
    connect: function () {
      console.log('socket connected')
    }
  },
  mounted () {
    this.$socket.emit('chat', '123123')
  }
}

My browser shows the following error:
TypeError: Cannot read property 'emit' of undefined

Anything I am wrong?

**Comment by dontlookup** [comment]
Hi, did you solve The issue ?

**Comment by felimartina** [comment]
Having the same issue, how did you end up solving it?

**Comment by dontlookup** [comment]
I think it was something with 'no ssr' in html tag

**Comment by felimartina** [comment]
I guess I was actually getting a different issue (same error though)
In my case was related to the scope of `this` and arrow functions. I was using an arrow function to define my custom methods. So when defining the socket method i was using:

```
...
,
  methods: {
    addServer: val => {
      const newServer = {
				name: this.newServerName,
				url: this.newServerUrl
			}
			this.$socket.emit("addServer", JSON.stringify(newServer))
			newServerName = ""
      newServerUrl = ""
    }
  }
...
```

And I shouldn't have used arrow functions here...or change the use of `this`


```
...
,
  methods: {
    addServer: function(val) {
      const newServer = {
				name: this.newServerName,
				url: this.newServerUrl
			}
			this.$socket.emit("addServer", JSON.stringify(newServer))
			newServerName = ""
      newServerUrl = ""
    }
  }
...
```
