### ISSUE TITLE
Support of Socket.io 2

### ISSUE THREAD

**Issue by cedriccouret** [MetinSeylan/Vue-Socket.io#88]
Hi,

I'm currently experiencing issues (dropping connections mostly), and realized that this package references socket.io-client version "^1.4.6" when I'm using version 2.0.3 on the server side.
I can't be 100% sure but I guess this version gap could be one of the sources of my problems.

Do you plan to support new versions of Socket.io ?

Thanks.

**Comment by abdulmueid** [comment]
Submitted pull request to update Socket.io client.
https://github.com/MetinSeylan/Vue-Socket.io/pull/89

No breaking changes. Everything on my existing project working as expected.
