### ISSUE TITLE
Updating socketio

### ISSUE THREAD

**Issue by judsin** [MetinSeylan/Vue-Socket.io#90]
how can i make this work so that i can change the token? 
if this is my code:

    import VueSocketio from 'vue-socket.io';
    import io from 'socket.io-client';
    import store from '../store';

    ...

    var token = 'randomtoken';
	const socketInstance = io('https://myserver.com', {
	    query: 'token=' + token
	});
	Vue.use(VueSocketio, socketInstance, store);

and i disconnect from the socket using: 

	(new Vue()).$socket.emit('disconnect');

if i run this again with a different token:

    var token = 'anotherrandomtoken';
	const socketInstance = io('https://myserver.com', {
	    query: 'token=' + token
	});
	Vue.use(VueSocketio, socketInstance, store);

it doesnt reconnect to the socket anymore?
i assume because the socketInstance or VueSocketio is still running and hasn't actually disconnected?

is there a workaround for this?

**Comment by judsin** [comment]
This is quite similar to my issue: https://webcache.googleusercontent.com/search?q=cache:nsrszFm5Cg0J:https://stackoverflow.com/questions/46627581/how-do-i-reset-socket-io-query-parameter-using-vue-socket-io+&cd=1&hl=en&ct=clnk&gl=au

**Comment by judsin** [comment]
if I add this check it updates the socket, but i guess VueSocketio isn't detecting the next socket details?

    if (typeof this.$socket !== 'undefined') {
        console.log('socket already initialised');
        delete Vue.prototype.$socket;
        Vue.prototype.$socket = socketInstance.connect();
    }

**Comment by judsin** [comment]
would it be possible to just add a new function in Main.js that destroys itself?

**Comment by felixheck** [comment]
push :)

**Comment by felixheck** [comment]
Hi @MetinSeylan, would you mind sharing the reasons for closing this issue?
Is there a new related release?

**Comment by suraw** [comment]
@judsin I want the same process as yours. What I did is do a `location.reload()`, generic javascript reload page to reload the main.js of vuejs.

**Comment by hasbug** [comment]
@suraw Could  you share your code?

**Comment by suraw** [comment]
Here's what I can share
This is the Login.vue
```
<template>
socket work here with query
</template>
<script>
export default {
  name: 'login',
  methods: {
    login: function () {
      var res = await login
      if (res) {
        location.reload()
      } else {
        alert('wrong credentials')
      }
    }
  }
}
</script>
```
This is my Splash.vue
```
<template>
  Socket is working here
</template>
<script>
export default {
  name: 'splash',
  mounted: {
    this.socket.connect()
  }
}
<script>
```
this will be my main.js
```
import Vue from 'vue'
import VueSocketio from 'vue-socket.io'
import io from 'socket.io-client'

Vue.use(VueSocketio, io(process.env.URL + process.env.PORT, {
  autoConnect: false,
  'query': 'token=' + token
}))
```
and on my router, I check if the user is logged(if token is set). so I only need location.reload() to refresh the connectin to socket with query.

**Comment by takielias** [comment]
@suraw Can you Share your Example code please? I could not figure it.
