### ISSUE TITLE
Custom Event Listener Name

### ISSUE THREAD

**Issue by RizkiHabibie** [MetinSeylan/Vue-Socket.io#92]
Is there any posibilities to create event listener from a variable?

let channel = "Event_" + 1; //=> Event_1
this.$options.sockets.channel = (message) => {
	this.fetchData();
};

So the channel name will be Event_1

**Comment by callum-messiter** [comment]
I solved this by using the bracket notation:

`
let customEventName = 'someName';
this.$options.sockets.[customEventName] = (message) => {
  // do something...
}
`
