### ISSUE TITLE
Two socket instances in one Vue app

### ISSUE THREAD

**Issue by man15h** [MetinSeylan/Vue-Socket.io#97]
Is it possible to use two different socket instances in a single component?

```
const socket1Instance = io('url_of_first_socket)
const socket2Instance = io('url_of_second_socket')
```

**Comment by codeasashu** [comment]
Not possible. I have made a pull request https://github.com/MetinSeylan/Vue-Socket.io/pull/98 so you can use this branch. I haven't included build files in those commits but you can go to my fork of this repo and download the build files individually. Let me know if anything breaks
